import type { AlphaReadinessReport } from './alpha-readiness';
import { buildAlphaHardProofBlockers } from './alpha-hard-proof-blockers';
import { requiredAlphaEvidence } from './alpha-required-evidence';

export function buildHostedSmokeChecklist(report: AlphaReadinessReport) {
	return {
		target: report.target,
		status: 'requires-external-host',
		requiredEnvironment: [
			{
				name: 'ALPHA_SMOKE_BASE_URL',
				required: true,
				description: 'Absolute public or CI-accessible HTTP(S) base URL for the deployed PHP host.'
			},
			{
				name: 'ALPHA_SMOKE_EXPECTED_VERSION',
				required: false,
				defaultValue: report.target,
				description: 'Expected alpha version marker embedded in report endpoints.'
			},
			{
				name: 'ALPHA_SMOKE_TIMEOUT_MS',
				required: false,
				defaultValue: '15000',
				description: 'Per-request timeout for hosted smoke checks.'
			},
			{
				name: 'ALPHA_SMOKE_REPORT_PATH',
				required: false,
				defaultValue: 'report/alpha-remote-smoke.json',
				description: 'Relative output path for hosted smoke evidence.'
			}
		],
		commands: [
			{
				command: 'bun run alpha:remote:smoke',
				purpose: 'Record hosted smoke evidence against the deployed PHP host.'
			},
			{
				command: 'bun run alpha:gate:hosted',
				purpose: 'Run local alpha gate, hosted smoke, report regeneration, and final report verification.'
			}
		],
		hardProofBlockerLedgerMarker: 'hard-proof-blocker-ledger',
		hardProofBlockers: buildAlphaHardProofBlockers(),
		coveredEndpoints: [
			'/',
			'/alpha-readiness',
			'/alpha-readiness/no-hydration',
			'/alpha-readiness/report.json',
			'/alpha-readiness/report.html',
			'/alpha-readiness/report.md',
			'/alpha-readiness/release-notes.md',
			'/alpha-readiness/release-checklist.md',
			'/alpha-readiness/report.svg',
			'/alpha-readiness/community-source-map.svg',
			'/alpha-readiness/release-manifest.json',
			'/alpha-readiness/gate-matrix.json',
			'/alpha-readiness/evidence-index.json',
			'/alpha-readiness/package-contract.json',
			'/alpha-readiness/native-host-contract.json',
			'/alpha-readiness/native-host-guide.md',
			'/alpha-readiness/native-host-wrapper-smoke.json',
			'/alpha-readiness/hosted-smoke-checklist.json',
			'/alpha-readiness/bridge-reuse.json',
			'/alpha-readiness/review-index.md',
			'/alpha-readiness/community-signals.json',
			'/alpha-readiness/community-analytics.md',
			'/alpha-readiness/community-research-pack.json',
			'/alpha-readiness/readiness.csv',
			'/alpha-readiness/community-signals.csv',
			'/alpha-readiness/community-sources.csv',
			'/form-basic',
			'POST /form-basic',
			'/_app/immutable/missing-alpha-smoke.js',
			'/_app/immutable/missing-alpha-smoke.css',
			'/alpha-readiness/missing-alpha-smoke.svg',
			'/alpha-readiness/missing-alpha-smoke.webmanifest',
			'/alpha-readiness/missing-alpha-smoke.wasm',
			'/alpha-readiness/missing-alpha-smoke.json'
		],
		contentExpectations: [
			{
				endpoint: '/alpha-readiness',
				markers: [
					'data-native-host-bridge-status',
					'data-native-platform-provenance',
					'data-window-material',
					'windows-11-mica',
					'data-macos-chrome',
					'data-windows-chrome',
					'data-native-platform-mode',
					'hybrid-proof',
					'Native host bridge',
					'data-native-host-handoff-controls',
					'browser fallback active',
					'data-ultragear-source-parity',
					'ultraGearParityContract',
					'data-desktop-shell-ui-binding',
					'desktopShellUiBinding',
					'@scriptgpt/desktop-shell-ui',
					'lg-ultragear-host-permission-checklist',
					'realHostPermissionChecklist',
					'hostPermissionCues',
					'requiredHostPermission',
					'src-tauri/capabilities/default.json',
					'enableMicaWindowChrome',
					'syncTaskbarProgress',
					'toggleWindowMaximize',
					'installSvelteKitPhpNativeHost',
					'data-progress-report-handoff',
					'progressReportHandoff',
					'statusMapping',
					'ProgressBarStatus.None',
					'report-ready',
					'data-native-visual-matrix',
					'native-visual-matrix',
					'windows-mica-visual-row',
					'macos-traffic-light-row',
					'macos-vibrancy-visual-row',
					'macos-vibrancy-host-policy',
					'macos-material-host-policy',
					'source-observed-macos-host-scaffold',
					'macos-native-vibrancy-unverified',
					'source-observed macOS host policy',
					'data-macos-material-host-policy',
					'data-macos-native-vibrancy',
					'data-alpha-proof-ledger',
					'data-required-alpha-evidence',
					'Required alpha evidence',
					'requiredEvidence',
					'required-alpha-evidence',
					...requiredAlphaEvidence,
					'proofLedger',
					'Alpha proof ledger',
					'alpha-over-rc-release-policy',
					'alpha-runtime-gate-ledger',
					'hosted-php-smoke-proof-required',
					'needs-local-gate-proof',
					'needs-hosted-proof',
					'data-community-keyword-search-graph',
					'data-analytics-linked-keyword-graph',
					'keywordSearchGraph',
					'analytics-linked-keyword-graph',
					'community-analytics-freshness-contract',
					'curated-signal-score',
					'collected-demand-score',
					'directional-community-signal',
					'no-live-community-api-runtime-boundary',
					'source-to-keyword-edge',
					'Community evidence coverage ledger',
					'Open-source analytics sources reviewers can audit first'
				],
				proves:
					'Hosted alpha readiness page exposes the live native-host bridge status panel, UltraGear source parity panel, alpha proof-ledger blockers, keyword-search graph panel, and open-source community evidence ledger without requiring a desktop wrapper.'
			},
			{
				endpoint: '/alpha-readiness/no-hydration',
				markers: [
					'no-hydration-fixture',
					'csr-disabled-prerender-contract',
					'theme-stable-ssr-html',
					'This fixture is intentionally prerendered with csr=false'
				],
				forbiddenMarkers: ['<script', 'sveltekit:start', 'data-sveltekit-hydrate'],
				proves:
					'Hosted no-hydration fixture serves stable prerendered csr=false HTML without client scripts or SvelteKit hydration markers that can repaint blog/static themes after load.'
			},
			{
				endpoint: '/alpha-readiness/report.html',
				markers: [
					'Native-styled release report',
					'app-window',
					'theme-ultragear',
					'data-window-effect="mica"',
					'data-window-focused="true"',
					'data-window-chrome-state="mica-active"',
					'data-transparent-webview-material-boundary="host-owned"',
					'transparent-webview-material-boundary',
					'data-macos-material-host-policy',
					'data-macos-native-vibrancy',
					'data-ultragear-html-report-shell',
					'topbar-drag-strip',
					'data-window-drag',
					'data-drag-block-selector',
					'data-no-window-drag',
					'data-window-control-group',
					'caption-button',
					'data-window-control="maximize"',
					'--blur-mica',
					'--surface-chrome',
					'--window-bg-mica',
					'--window-bg-inactive',
					'--window-wash-inactive',
					'--caption-hover-bg',
					'max-width: 1180px',
					'max-width: 860px',
					'alpha-community-source-evidence-checklist',
					'source-health-classification',
					'result-total-field-contract',
					'top-result-field-contract',
					'sample-review-rule',
					'releaseUse',
					'blockedOutcomePolicy'
				],
				proves:
					'Hosted standalone HTML report preserves the UltraGear app-window, Mica, topbar, caption-control, responsive shell, and community source-evidence checklist markers for screenshot/release review.'
			},
			{
				endpoint: '/alpha-readiness/report.json',
				markers: [
					'releasePolicy',
					'alphaReleaseChecklist',
					'source-controlled-release-documentation',
					'docs/ALPHA-RELEASE-CHECKLIST.md',
					'/alpha-readiness/release-checklist.md',
					'report/alpha-release-checklist.md',
					'requiredEvidence',
					...requiredAlphaEvidence,
					'proofLedger',
					'alpha-over-rc-release-policy',
					'1.0.2-alpha',
					'above-rc',
					'alpha-runtime-gate-ledger',
					'hosted-php-smoke-proof-required'
				],
				proves:
					'Hosted canonical report JSON exposes release policy, required alpha evidence, and proof-ledger boundaries.'
			},
			{
				endpoint: '/alpha-readiness/native-host-contract.json',
				markers: [
					'native-window-action',
					'start-dragging',
					'toggle-maximize',
					'set-window-effect',
					'set-progress',
					'clear-progress',
					'report-ready',
					'setWindowEffect',
					'setProgress',
					'clearProgress',
					'reportReady',
					'__SVELTEKIT_PHP_NATIVE_HOST__',
					'__SVELTEKIT_PHP_NATIVE_HOST_HISTORY__',
					'browser-fallback',
					'theme-ultragear',
					'visualSnapshotContract',
					'nativeVisualMatrix',
					'native-visual-matrix',
					'windows-mica-visual-row',
					'macos-traffic-light-row',
					'macos-vibrancy-visual-row',
					'macos-vibrancy-host-policy',
					'macos-material-host-policy',
					'source-observed-macos-host-scaffold',
					'macos-native-vibrancy-unverified',
					'data-macos-material-host-policy',
					'data-macos-native-vibrancy',
					'windows-caption-control-row',
					'ultragear-theme-row',
					'browser-fallback-visual-row',
					'ultraGearSourceParity',
					'progressReportHandoff',
					'native-host-compatibility-matrix',
					'source-observed-host-compatibility-contract',
					'packages/ultragear-widget-ui/src/app.ts',
					'features.micaSupported',		'windowChromeState',
		'mica-active',
		'mica-inactive',
		'plain',
		'webview.setBackgroundColor([0, 0, 0, 0])',
					'ShellFeatureProbe.mica_supported',
					'current_shell_features()',
					'cfg!(target_os = "windows")',
					'windows-mica-effects',
					'taskbar-progress-reporting',
					'native-titlebar-drag-maximize',
					'ProgressBarStatus.Indeterminate',
					'ProgressBarStatus.None',
					'lg-ultragear-host-permission-checklist',
					'realHostPermissionChecklist',
					'real-host-permission-cue-required',
					'hostPermissionCues',
					'requiredHostPermission',
					'src-tauri/capabilities/default.json',
					'core:window:allow-set-effects',
					'core:window:allow-set-progress-bar',
					'core:window:allow-start-dragging',
					'core:window:allow-toggle-maximize',
					'report-ready',
					'desktopShellUiBinding',
					'@scriptgpt/desktop-shell-ui',
					'packages/desktop-shell-ui/src/index.ts',
					'enableMicaWindowChrome',
					'syncTaskbarProgress',
					'toggleWindowMaximize',
					'native-host-wrapper-probe',
					'native-host-wrapper-smoke',
					'data-drag-block-selector',
					'caption-button',
					'progressStatus',
					'indeterminate',
					'applyWindowChrome',
					'data-window-control'
				],
				proves:
					'Hosted native-host contract exposes the browser-safe UltraGear-style host event seam and platform chrome markers.'
			},
			{
				endpoint: '/alpha-readiness/native-host-guide.md',
				markers: [
					'native host binding guide',
					'data-native-host-handoff-controls',
					'native-window-action',
					'set-window-effect',
					'set-progress',
					'clear-progress',
					'report-ready',
					'setWindowEffect',
					'setProgress',
					'clearProgress',
					'reportReady',
					'window.__SVELTEKIT_PHP_NATIVE_HOST__',
					'window.__SVELTEKIT_PHP_NATIVE_HOST_HISTORY__',
					'Effect.Mica',
					'lg-ultragear-host-permission-checklist',
					'realHostPermissionChecklist',
					'hostPermissionCues',
					'requiredHostPermission',
					'src-tauri/capabilities/default.json',
					'desktopShellUiBinding',
					'installSvelteKitPhpNativeHost',
					'@scriptgpt/desktop-shell-ui',
					'packages/desktop-shell-ui/src/index.ts',
					'enableMicaWindowChrome',
					'syncTaskbarProgress',
					'toggleWindowMaximize',
					'bindColorSchemeWatcher',
					'prefersDarkMode',
					'window.matchMedia("(prefers-color-scheme: dark)")',
					'win.setProgressBar',
					'reportJson',
					'native-host-wrapper-probe',
					'native-host-wrapper-smoke',
					'native-host-wrapper-event-replay',
					'native-host-wrapper-event-replay-step',
					'eventReplayTranscript[]',
					'expectedHistoryResult',
					'expectedDesktopShellUiHelper',
					'noFallbackAllowedForRealHost'
				],
				proves:
					'Hosted native host guide gives desktop wrappers a concrete binding path for Mica, titlebar, progress, report-ready handoff, and deterministic native-window-action replay without native imports in the adapter.'
			},
			{
				endpoint: '/alpha-readiness/native-host-wrapper-smoke.json',
				markers: [
					'native-host-wrapper-smoke',
					'native-host-wrapper-probe',
					'contract-ready',
					'native-host-wrapper-event-replay',
					'native-host-wrapper-event-replay-step',
					'realHostVerified',
					'buildNativeHostWrapperProbe',
					'toDesktopShellUiTaskbarProgressState',
					'enableMicaWindowChrome',
					'syncTaskbarProgress',
					'toggleWindowMaximize',
					'TaskbarProgressState',
					'set-window-effect',
					'set-progress',
					'clear-progress',
					'report-ready',
					'expectedHistoryResult',
					'expectedDesktopShellUiHelper',
					'window.__SVELTEKIT_PHP_NATIVE_HOST_HISTORY__',
					'noFallbackAllowedForRealHost'
				],
				proves:
					'Hosted wrapper smoke endpoint exposes deterministic handoff data for optional Windows/macOS host smoke without importing native APIs into the adapter runtime.'
			},
			{
				endpoint: '/alpha-readiness/bridge-reuse.json',
				markers: [
					'pointerdown',
					'native-window-action',
					'NativeTitlebar.svelte',
					'NativeHostBridgeStatus.svelte',
					'native-host-event-bridge.ts',
					'data-native-host-bridge-status',
					'data-native-host-handoff-controls',
					'set-window-effect',
					'set-progress',
					'clear-progress',
					'report-ready',
					'__SVELTEKIT_PHP_NATIVE_HOST__',
					'ultraGearParityContract',
					'nativeVisualMatrix',
					'native-visual-matrix',
					'native-host-compatibility-matrix',
					'source-observed-host-compatibility-contract',
					'macos-material-host-policy',
					'source-observed-macos-host-scaffold',
					'macos-native-vibrancy-unverified',
					'data-macos-material-host-policy',
					'data-macos-native-vibrancy',
					'packages/ultragear-widget-ui/src/app.ts',
					'features.micaSupported',
					'windowChromeState',
					'mica-active',
					'mica-inactive',
					'plain',
					'webview.setBackgroundColor([0, 0, 0, 0])',
					'ShellFeatureProbe.mica_supported',
					'current_shell_features()',
					'cfg!(target_os = "windows")',
					'MacosLauncher::LaunchAgent',
					'mica_supported: cfg!(target_os = "windows")',
					'windows-mica-effects',
					'taskbar-progress-reporting',
					'native-titlebar-drag-maximize',
					'progressReportHandoff',
					'packages/desktop-shell-ui/src/index.ts',
					'desktopShellUiBinding',
					'installSvelteKitPhpNativeHost',
					'enableMicaWindowChrome',
					'syncTaskbarProgress',
					'toggleWindowMaximize',
					'bindColorSchemeWatcher',
					'prefersDarkMode',
					'data-drag-block-selector',
					'caption-button',
					'progressStatus',
					'indeterminate',
					'applyWindowChrome',
					'syncWindowProgress',
					'ProgressBarStatus.Indeterminate',
					'ProgressBarStatus.None',
					'report-ready',
					'DRAG_START_THRESHOLD_PX',
					'Structured report preview',
					'lg-ultragear-native-platform-provenance',
					'Effect.Mica',
					'win.setEffects',
					'app-window',
					'app-window.maximized',
					':root[data-window-effect="mica"][data-window-focused="false"]',
					'theme-ultragear',
					'--window-bg-mica',
					'--window-bg-inactive',
					'--window-wash-inactive',
					'--surface-chrome',
					'max-width: 1180px',
					'max-width: 860px',
					'data-native-platform',
					'data-window-control-group',
					'[data-no-window-drag]',
					'dragBlockSelector',
					'setPointerCapture',
					'lostpointercapture',
					'window blur drag cancellation',
					'win.startDragging',
					'win.setProgressBar',
					'reportJson',
					'reportUrl',
					'set-window-effect',
					'set-progress',
					'clear-progress',
					'setWindowEffect',
					'setProgress',
					'clearProgress',
					'reportReady'
				],
				proves:
					'Hosted bridge reuse inventory records the pointer-threshold drag behavior, adapter-side host event cue, concrete UltraGear source parity map, and exact native platform provenance cues.'
			},
			{
				endpoint: '/alpha-readiness/community-analytics.md',
				markers: [
					'Source coverage plan',
					'Evidence kinds',
					'Collection risk',
					'community-analytics-freshness-contract',
					'Reviewer action:',
					'Collector note:'
				],
				proves:
					'Hosted community analytics handoff exposes source coverage, reviewer action, and collector-risk language.'
			},
			{
				endpoint: '/alpha-readiness/report.svg',
				markers: [
					'data-required-alpha-evidence',
					'Required alpha evidence',
					'requiredEvidence',
					'required-alpha-evidence',
					...requiredAlphaEvidence,
					'data-alpha-proof-ledger',
					'proofLedger',
					'alpha-over-rc-release-policy',
					'alpha-runtime-gate-ledger',
					'hosted-php-smoke-proof-required',
					'needs-local-gate-proof',
					'needs-hosted-proof',
					'progressReportHandoff',
					'native-visual-matrix',
					'data-native-platform-provenance',
					'data-native-host-handoff-controls',
					'No-hydration prerender proof',
					'/alpha-readiness/no-hydration',
					'theme-stable-ssr-html',
					'data-sveltekit-hydrate',
					'desktopShellUiBinding',
					'@scriptgpt/desktop-shell-ui',
					'installSvelteKitPhpNativeHost',
					'enableMicaWindowChrome',
					'syncTaskbarProgress',
					'toggleWindowMaximize',
					'set-window-effect',
					'set-progress',
					'clear-progress',
					'lg-ultragear-native-platform-provenance',
					'Effect.Mica',
					'win.setEffects',
					'lg-ultragear-host-permission-checklist',
					'realHostPermissionChecklist',
					'hostPermissionCues',
					'requiredHostPermission',
					'src-tauri/capabilities/default.json',
					'core:window:allow-set-effects',
					'core:window:allow-set-progress-bar',
					'core:window:allow-start-dragging',
					'core:window:allow-toggle-maximize',
					'app-window.maximized',
					'theme-ultragear',
					'setPointerCapture',
					'lostpointercapture',
					'win.startDragging',
					'reportJson',
					'analytics-linked-keyword-graph'
				],
				proves:
					'Hosted report graphic exposes native/progress report cues, native platform provenance, open-source analytics linkage, and alpha proof-ledger blockers as portable SVG evidence.'
			},
			{
				endpoint: '/alpha-readiness/community-source-map.svg',
				markers: [
					'keyword-search-graph',
					'analytics-linked-keyword-graph',
					'community-analytics-freshness-contract',
					'source-to-keyword-edge',
					'supported-api-lanes',
					'manual-research-lanes',
					'curated-signal-score',
					'collected-demand-score',
					'directional-community-signal',
					'no-live-community-api-runtime-boundary',
					'alpha-community-source-evidence-checklist',
					'source-health-classification',
					'result-total-field-contract',
					'top-result-field-contract',
					'sample-review-rule',
					'resultTotalField',
					'topResultFieldCount',
					'api.github.com/search'
				],
				proves:
					'Hosted source-map graphic exposes keyword-to-source graph markers linking alpha keyword research to API lanes, manual links, source-risk evidence, curated scores, and collected-demand-score handoff fields.'
			},
			{
				endpoint: '/alpha-readiness/release-checklist.md',
				markers: [
					'1.0.2-alpha release checklist',
					'alpha-over-rc-release-policy',
					'desktop-shell-ui-command-mapping',
					'community-analytics-csv-linkage',
					'router-path-safety-artifact-sync',
					'adapter-platform-emulation',
					'deploy-env-preflight-safety',
					'bun run alpha:gate',
					'bun run alpha:gate:hosted',
					'getDesktopShellUiCommandMapping',
					'sourceToKeywordEdge',
					'result-total-field-contract',
					'top-result-field-contract',
					'sample-review-rule',
					'resultTotalField',
					'topResultFields',
					'sampleReviewRule',
					'weighted_demand_score',
					'result_total_field',
					'top_result_fields',
					'sample_review_rule',
					'ALPHA_SMOKE_BASE_URL'
				],
				proves:
					'Hosted release checklist endpoint exposes the human alpha policy, native mapping, community linkage, source field contracts, runtime safety, and hosted proof checklist.'
			},
			{
				endpoint: '/alpha-readiness/community-research-pack.json',
				markers: [
					'providerCoverage',
					'evidenceKindCoverage',
					'collectionRiskCoverage',
					'collectionPlan',
					'keywordSearchGraph',
					'sourceToKeywordEdge',
					'analyticsLinkageMarker',
					'weightedDemandScore',
					'freshnessMaxAgeHours',
					'trustBoundary',
					'manualReviewRequired',
					'alpha-community-source-evidence-checklist',
					'source-health-classification',
					'result-total-field-contract',
					'top-result-field-contract',
					'sample-review-rule',
					'resultTotalField',
					'topResultFields',
					'sampleReviewRule',
					'analyticsFreshnessContract',
					'community-analytics-freshness-contract',
					'maxAgeHours',
					'community-analytics-graphic-linkage-contract',
					'communityAnalyticsGraphicLinkageContract',
					'community-source-map.svg',
					'community-analytics.md',
					'community-signals.csv',
					'community-sources.csv',
					'curated-signal-score',
					'collected-demand-score',
					'directional-community-signal',
					'no-live-community-api-runtime-boundary',
					'alpha-community-source-evidence-checklist',
					'source-health-classification',
					'result-total-field-contract',
					'top-result-field-contract',
					'sample-review-rule',
					'resultTotalField',
					'topResultFields',
					'sampleReviewRule'
				],
				proves:
					'Hosted research pack includes the open-source source taxonomy, collection plan, and graphic-to-analytics review contract.'
			},
			{
				endpoint: '/alpha-readiness/readiness.csv',
				markers: [
					'proof-ledger',
					'required-evidence',
					'requiredEvidence',
					'required-alpha-evidence',
					'native-host-binding-guide',
					'csr-disabled-prerender-contract',
					'windows-11-mica-browser-safe-shell',
					'macos-style-native-titlebar-rhythm',
					'alpha-readiness-report-graphics',
					'community-keyword-search-graph',
					'community-analytics-freshness-contract',
					'hosted-php-smoke-proof',
					'alpha-over-rc-release-policy',
					'native-visual-matrix',
					'analytics-linked-keyword-graph',
					'alpha-runtime-gate-ledger',
					'hosted-php-smoke-proof-required'
				],
				proves:
					'Hosted readiness CSV exposes spreadsheet-visible alpha proof ledger rows and stable blockers.'
			},
			{
				endpoint: '/alpha-readiness/community-signals.csv',
				markers: [
					'analytics_linkage_marker',
					'analytics-linked-keyword-graph',
					'weighted_demand_score',
					'source_to_keyword_edges',
					'curated_signal_score_marker',
					'curated-signal-score',
					'collected_demand_score_marker',
					'collected-demand-score',
					'directional_trust_level',
					'directional-community-signal',
					'no-live-community-api-runtime-boundary'
				],
				proves:
					'Hosted community signals CSV exposes spreadsheet-visible links between curated scores, collected demand scores, and the directional community-signal trust model.'
			},
			{
				endpoint: '/alpha-readiness/community-sources.csv',
				markers: [
					'evidence_kind',
					'collection_risk',
					'collection_method',
					'freshness_max_age_hours',
					'evidence_weight',
					'trust_boundary',
					'source_health',
					'analytics_linkage_marker',
					'alpha_evidence_checklist_marker',
					'alpha_evidence_checklist',
					'source_to_keyword_edge',
					'manual_review_required',
					'release_use',
					'reviewer_action',
					'collector_note',
					'blocked_outcome_policy',
					'result_total_field',
					'top_result_fields',
					'sample_review_rule'
				],
				proves:
					'Hosted CSV handoff includes spreadsheet-visible source taxonomy, source-to-keyword edges, freshness/trust fields, reviewer guidance, and result/top-result/sample-review field contracts.'
			},
			{
				endpoint: '/alpha-readiness/release-manifest.json',
				markers: [
					'trustModel',
					'releasePolicy',
					'proofLedger',
					'alpha-over-rc-release-policy',
					'1.0.2-alpha',
					'above-rc',
					'alpha-runtime-gate-ledger',
					'hosted-php-smoke-proof-required',
					'hostedProofInterpretation',
					'hosted-php-smoke-proof',
					'alphaEvidenceStatus',
					'real-php-host-smoke-evidence',
					'hostedSmokeStatus',
					'proofStage',
					'directional-community-signal',
					'no-live-community-api-runtime-boundary',
					'evidenceSurfaces',
					'nativeChromeVisualContract',
					'nativeVisualMatrix',
					'ultraGearSourceParity',
					'nativePlatformProvenance',
					'lg-ultragear-native-platform-provenance',
					'progressReportHandoff',
					'progressReportGraphic',
					'nativeHostBridgeStatus',
					'nativeHostBindingGuide',
					'communityKeywordSearchGraph',
					'communityAnalyticsFreshnessContract',
					'macos-material-host-policy',
					'source-observed-macos-host-scaffold',
					'macos-native-vibrancy-unverified',
					'data-macos-material-host-policy',
					'data-macos-native-vibrancy',
					'requiredEvidence',
					...requiredAlphaEvidence,
					'communityEvidenceLedger'
				],
				proves:
					'Hosted release manifest distinguishes generated artifacts, public-source analytics, runtime endpoints, live evidence surfaces, and hosted smoke proof.'
			},
			{
				endpoint: '/alpha-readiness/gate-matrix.json',
				markers: [
					'live-evidence-surfaces',
					'data-desktop-shell-ui-binding',
					'desktopShellUiBinding',
					'@scriptgpt/desktop-shell-ui',
					'installSvelteKitPhpNativeHost',
					'enableMicaWindowChrome',
					'syncTaskbarProgress',
					'toggleWindowMaximize',
					'data-drag-block-selector',
					'caption-button',
					'progressStatus',
					'indeterminate',
					'sourceToKeywordEdge',
					'analyticsLinkageMarker',
					'weightedDemandScore',
					'freshnessMaxAgeHours',
					'trustBoundary',
					'manualReviewRequired',
					'alpha-community-source-evidence-checklist',
					'source-health-classification',
					'required-alpha-evidence',
					'requiredEvidence',
					...requiredAlphaEvidence,
					'release-policy-evidence-boundary',
					'live-runtime-surface-proof',
					'artifact-sync',
					'local-alpha-gate',
					'hosted-alpha-gate',
					'report/alpha-bridge-reuse.json',
					'report/alpha-release-checklist.md',
					'/alpha-readiness/release-checklist.md',
					'native platform provenance',
					'Native platform provenance markers',
					'Desktop shell helper binding markers',
					'report/alpha-readiness.json'
				],
				proves:
					'Hosted gate matrix exposes the live-evidence proof gate, native provenance artifacts, and artifact-sync release gate used by alpha reviewers.'
			},
			{
				endpoint: '/alpha-readiness/evidence-index.json',
				markers: [
					'liveEvidenceSurfaces',
					'native-host-bridge-status',
					'data-native-host-handoff-controls',
					'native-visual-matrix',
					'lg-ultragear-native-platform-provenance',
					'progress-report-handoff',
					'progress-report-graphic',
					'required-alpha-evidence',
					'requiredEvidence',
					...requiredAlphaEvidence,
					'alpha-release-checklist',
					'/alpha-readiness/release-checklist.md',
					'report/alpha-release-checklist.md',
					'community-evidence-coverage-ledger',
					'data-native-host-bridge-status',
					'data-native-host-handoff-controls',
					'Open-source analytics sources reviewers can audit first'
				],
				proves:
					'Hosted evidence index exposes machine-readable live native-host and community-ledger proof surfaces.'
			},
			{
				endpoint: '/alpha-readiness/package-contract.json',
				markers: [
					'sveltekit-php/adapter',
					'alpha:consumer:smoke',
					'publishConfig',
					'alpha-over-rc-release-policy',
					'above-rc',
					'verify:artifacts',
					'precheck:deploy',
					'source-to-generated-bundle-check',
					'environment-preflight-check',
					'nativePlatformProvenanceProof',
					'lg-ultragear-native-platform-provenance',
					'real-host-permission-checklist',
					'lg-ultragear-host-permission-checklist',
					'realHostPermissionChecklist',
					'hostPermissionCues',
					'requiredHostPermission',
					'src-tauri/capabilities/default.json',
					'alphaReleaseChecklistProof',
					'windowChromeState',
					'mica-active',
					'mica-inactive',
					'plain',
					'webview.setBackgroundColor([0, 0, 0, 0])',
					'data-window-chrome-state',
					'data-window-chrome-state="mica-active"',
					'transparent-webview-material-boundary',
					'data-transparent-webview-material-boundary="host-owned"',
					'macos-material-host-policy',
					'source-observed-macos-host-scaffold',
					'macos-native-vibrancy-unverified',
					'data-macos-material-host-policy',
					'data-macos-native-vibrancy',
					'/alpha-readiness/release-checklist.md',
					'report/alpha-release-checklist.md',
					'docs/ALPHA-RELEASE-CHECKLIST.md',
					'TaskbarProgressState',
					'toDesktopShellUiTaskbarProgressState',
					'native-host-wrapper-probe',
					'saveInFlight',
					'refreshInFlight',
					'hasQueuedSave',
					'bindColorSchemeWatcher',
					'prefersDarkMode',
					'window.matchMedia("(prefers-color-scheme: dark)")',
					'app-window.maximized',
					'theme-ultragear',
					'setPointerCapture',
					'lostpointercapture',
					'nativeHostBindingGuideProof',
					'native host binding guide',
					'noHydrationPrerenderProof',
					'csr-disabled-prerender-contract',
					'theme-stable-ssr-html',
					'/alpha-readiness/native-host-guide.md',
					'report/alpha-native-host-guide.md',
					'nativeHostWrapperSmokeProof',
					'deterministic-host-wrapper-handoff',
					'realHostVerified',
					'noNativeApiBoundary',
					'window.__SVELTEKIT_PHP_NATIVE_HOST__',
					'native-host-wrapper-event-replay',
					'native-host-wrapper-event-replay-step',
					'window.__SVELTEKIT_PHP_NATIVE_HOST_HISTORY__',
					'expectedHistoryResult',
					'expectedDesktopShellUiHelper',
					'noFallbackAllowedForRealHost',
					'%2e%2e/.env',
					'/alpha-readiness/native-host-wrapper-smoke.json',
					'report/alpha-native-host-wrapper-smoke.json',
					'native-host-wrapper-smoke',
					'requiredEvidence',
					...requiredAlphaEvidence,
					'set-window-effect',
					'set-progress',
					'clear-progress',
					'report-ready'
				],
				proves:
					'Hosted package contract exposes the adapter package surface, external consumer smoke, strict artifact-sync proof, deploy precheck proof, native platform provenance proof, and deterministic wrapper-smoke boundary without publishing or deploying.'
			}
		],
		securityProbes: [
			'%2e%2e/package.json',
			'..%2Fpackage.json',
			'%2e%2e/.env',
			'..%2F.env',
			'_app/%2e%2e/%2e%2e/package.json'
		],
		assetFallbackExclusions: [
			{
				endpoint: '/_app/immutable/missing-alpha-smoke.js',
				proves: 'Missing generated JavaScript asset paths do not receive route fallback HTML.'
			},
			{
				endpoint: '/_app/immutable/missing-alpha-smoke.css',
				proves: 'Missing generated CSS asset paths do not receive route fallback HTML.'
			},
			{
				endpoint: '/alpha-readiness/missing-alpha-smoke.svg',
				proves: 'Missing SVG asset-like paths do not receive route fallback HTML.'
			},
			{
				endpoint: '/alpha-readiness/missing-alpha-smoke.webmanifest',
				proves: 'Missing webmanifest asset-like paths do not receive route fallback HTML.'
			},
			{
				endpoint: '/alpha-readiness/missing-alpha-smoke.wasm',
				proves: 'Missing WASM asset-like paths do not receive route fallback HTML.'
			},
			{
				endpoint: '/alpha-readiness/missing-alpha-smoke.json',
				proves: 'Missing JSON asset-like paths do not receive route fallback HTML.'
			}
		],
		proofArtifact: 'report/alpha-remote-smoke.json',
		completionRule:
			'The alpha can be considered hosted-proven only when bun run alpha:gate:hosted passes with ALPHA_SMOKE_BASE_URL set to a real deployed PHP host.'
	};
}

