import { requiredAlphaEvidence } from './alpha-required-evidence';
import { alphaTarget } from './alpha-readiness';

export function renderAlphaReleaseChecklistMarkdown() {
	const lines = [
		'# SvelteKit PHP 1.0.2-alpha release checklist',
		'',
		`Candidate: \`${alphaTarget}\``,
		'',
		'This checklist defines the project-specific `1.0.2-alpha` bar. In this repo, `1.0.2-alpha` is the required pre-stable release track and is treated as above any RC label for project planning. This is a project policy, not generic SemVer prerelease ordering.',
		'',
		'## Required evidence markers',
		'',
		...requiredAlphaEvidence.map((marker) => `- \`${marker}\``),
		'',
		'## Local alpha gate',
		'',
		'```powershell',
		'bun run alpha:report:full',
		'bun run verify:alpha',
		'bun run verify:release-prep',
		'bun run alpha:gate',
		'```',
		'',
		'The local gate must regenerate reports, verify release-prep safety, rebuild the adapter, run strict artifact sync, run unit/runtime checks, and run the consumer smoke.',
		'',
		'## Hosted alpha gate',
		'',
		'```powershell',
		'$env:ALPHA_SMOKE_BASE_URL = "https://example.com"',
		'bun run alpha:gate:hosted',
		'```',
		'',
		'`ALPHA_SMOKE_BASE_URL` must be an HTTP(S) origin/path without credentials or query tokens. Hosted smoke is not pass evidence until it targets a real deployed PHP host.',
		'',
		'## Native shell evidence',
		'',
		'- Reuse cue package: `@scriptgpt/desktop-shell-ui`',
		'- Source cue: `packages/desktop-shell-ui/src/index.ts`',
		'- Widget cue: `packages/ultragear-widget-ui/src/app.ts`',
		'- Host global: `window.__SVELTEKIT_PHP_NATIVE_HOST__`',
		'- Installer marker: `installSvelteKitPhpNativeHost`',
		'- Mapping marker: `getDesktopShellUiCommandMapping`',
		'- Progress translation marker: `toDesktopShellUiTaskbarProgressState`',
		'',
		'Required action-to-helper mapping:',
		'',
		'- `start-dragging` -> `win.startDragging()`',
		'- `toggle-maximize` -> `toggleWindowMaximize(win)`',
		'- `set-window-effect` -> `enableMicaWindowChrome(win)`',
		'- `set-progress` -> `syncTaskbarProgress(win, { saveInFlight: progressStatus === "indeterminate", refreshInFlight: false, hasQueuedSave: progressStatus === "normal" })`',
		'- `clear-progress` -> `syncTaskbarProgress(win, { saveInFlight: false, refreshInFlight: false, hasQueuedSave: false })`',
		'- `report-ready` -> `host.reportReady(...)`',
		'',
		'The PHP adapter must remain browser/PHP-host safe. Tauri APIs belong only in an optional native wrapper.',
		'',
		'## Community analytics evidence',
		'',
		'- `sourceToKeywordEdge`',
		'- `analyticsLinkageMarker`',
		'- `weightedDemandScore`',
		'- `freshnessMaxAgeHours`',
		'- `trustBoundary`',
		'- `manualReviewRequired`',
		'- `weighted_demand_score`',
		'- `source_to_keyword_edges`',
		'- `source_to_keyword_edge`',
		'',
		'Community counts are directional public-source signals, not telemetry and not release claims by themselves.',
		'',
		'## Runtime and artifact safety',
		'',
		'- root `router.php` delegates to generated runtime routing',
		'- generated routers reject traversal, encoded separators, control/null bytes, and protected paths',
		'- checked-in `adapter/index.js` is synchronized with source',
		'- deploy and hosted smoke commands fail on empty, placeholder, or unsafe environment values',
		'',
		'## Stable blocker',
		'',
		'Stable `1.0.0` remains blocked until hosted PHP smoke passes against a real deployment and all required alpha evidence markers are regenerated and verified from current source.',
		''
	];

	return lines.join('\n');
}

