import { buildBridgeReuseInventory } from './alpha-bridge-reuse';
import { buildAlphaNativeHostContract } from './alpha-native-host-contract';
import type { AlphaReadinessReport } from './alpha-readiness';

export function renderAlphaNativeHostGuideMarkdown(report: AlphaReadinessReport) {
	const contract = buildAlphaNativeHostContract(report);
	const bridgeReuse = buildBridgeReuseInventory(report);
	const runtimeBridge = contract.hostRuntimeBridge;
	const eventActions = contract.hostEvents.flatMap((event) => event.actions);
	const nativePlatformProvenance = bridgeReuse.nativePlatformProvenance;
	const progressReportHandoff = bridgeReuse.progressReportHandoff;
	const lines = [
		`# SvelteKit PHP ${report.target} native host binding guide`,
		'',
		`Issued: ${report.issued}`,
		`Bridge source: ${report.bridgeSource}`,
		'',
		'This guide is the alpha handoff for a Windows/macOS desktop wrapper. The PHP adapter runtime remains browser-safe: no Tauri imports, no native window calls, and no host APIs are required for hosted PHP demos.',
		'',
		'## Runtime boundary',
		'',
		`- Runtime bridge: \`${runtimeBridge.source}\``,
		`- Mounted by: \`${runtimeBridge.mountedBy}\``,
		`- Global controller: \`${runtimeBridge.globalController}\``,
		`- Global history: \`${runtimeBridge.globalHistory}\``,
		`- Result modes: ${runtimeBridge.resultModes.map((mode) => `\`${mode}\``).join(', ')}`,
		'- Hosted browser fallback records deterministic history instead of silently dropping commands.',
		'',
		'## Required host handlers',
		'',
		...runtimeBridge.handlers.map((handler) => `- \`${handler}\``),
		'',
		'## Supported `native-window-action` actions',
		'',
		...eventActions.map((action) => `- \`${action}\``),
		'',
		'## Event detail shape',
		'',
		'```ts',
		'type NativeWindowActionDetail = {',
		"  action: 'start-dragging' | 'toggle-maximize' | 'set-window-effect' | 'set-progress' | 'clear-progress' | 'report-ready';",
		'  source?: string;',
		'  dragStartThresholdPx?: number;',
		"  windowEffect?: 'mica' | 'acrylic' | 'none';",
		'  progress?: number;',
		"  progressStatus?: 'indeterminate' | 'normal' | 'none';",
		'  reportHref?: string;',
		"  reportKind?: 'json' | 'html' | 'markdown' | 'svg' | 'csv' | 'bundle';",
		'  reportLabel?: string;',
		'};',
		'```',
		'',
		'## Browser-side registration shape',
		'',
		'```ts',
		'window.__SVELTEKIT_PHP_NATIVE_HOST__ = {',
		'  startDragging(detail) {',
		'    // Windows/macOS host starts native titlebar drag.',
		'  },',
		'  toggleMaximize(detail) {',
		'    // Host toggles maximized/restored window bounds.',
		'  },',
		'  setWindowEffect(detail) {',
		'    // Map detail.windowEffect === "mica" to Windows 11 Mica where supported.',
		'  },',
		'  setProgress(detail) {',
		'    // Map detail.progressStatus/detail.progress to taskbar or dock progress.',
		'  },',
		'  clearProgress(detail) {',
		'    // Clear taskbar or dock progress state.',
		'  },',
		'  reportReady(detail) {',
		'    // Open, reveal, copy, or badge the generated report bundle link.',
		'  }',
		'};',
		'```',
		'',
		'## LG UltraGear desktop-shell binding recipe',
		'',
		'- Source package: `packages/desktop-shell-ui/src/index.ts`.',
		'- Upstream widget source: `packages/ultragear-widget-ui/src/app.ts`.',
		'- Package name: `@scriptgpt/desktop-shell-ui`.',
		'- Reused helpers: `enableMicaWindowChrome`, `syncTaskbarProgress`, `toggleWindowMaximize`, `bindColorSchemeWatcher`, `prefersDarkMode`, and `TaskbarProgressState`.',
		'- Native cue mapping: `Effect.Mica`, `ProgressBarStatus.Indeterminate`, `ProgressBarStatus.Normal`, `ProgressBarStatus.None`, and `progress: 18`.',
		'- Adapter marker: `desktopShellUiBinding` / `installSvelteKitPhpNativeHost` / `getDesktopShellUiCommandMapping` / `toDesktopShellUiTaskbarProgressState`.',
		'- Progress translation: adapter `progressStatus` maps to `TaskbarProgressState` fields `saveInFlight`, `refreshInFlight`, and `hasQueuedSave` before calling `syncTaskbarProgress`.',
		'',
		'```ts',
		"import { getCurrentWindow } from '@tauri-apps/api/window';",
		"import { enableMicaWindowChrome, syncTaskbarProgress, toggleWindowMaximize } from '@scriptgpt/desktop-shell-ui';",
		'',
		'export function installSvelteKitPhpNativeHost() {',
		'  const win = getCurrentWindow();',
		'',
		'  window.__SVELTEKIT_PHP_NATIVE_HOST__ = {',
		'    startDragging() {',
		'      void win.startDragging();',
		'    },',
		'    toggleMaximize() {',
		'      void toggleWindowMaximize(win);',
		'    },',
		'    setWindowEffect(detail) {',
		'      if (detail.windowEffect === "mica") void enableMicaWindowChrome(win);',
		'    },',
		'    setProgress(detail) {',
		'      void syncTaskbarProgress(win, {',
		'        saveInFlight: detail.progressStatus === "indeterminate",',
		'        refreshInFlight: false,',
		'        hasQueuedSave: detail.progressStatus === "normal"',
		'      });',
		'    },',
		'    clearProgress() {',
		'      void syncTaskbarProgress(win, { saveInFlight: false, refreshInFlight: false, hasQueuedSave: false });',
		'    },',
		'    reportReady(detail) {',
		'      console.info("SvelteKit PHP alpha report ready", detail.reportHref);',
		'    }',
		'  };',
		'}',
		'```',
		'',
		'The package import above belongs only in an optional Tauri/native wrapper. Do not add `@tauri-apps/api` or the UltraGear helper package to the PHP adapter runtime bundle.',
		'',
		'## Live alpha proof surface',
		'',
		'- Route: `/alpha-readiness`',
		'- Status marker: `data-native-host-bridge-status`',
		'- Handoff controls marker: `data-native-host-handoff-controls`',
		'- Contract endpoint: `/alpha-readiness/native-host-contract.json`',
		'- Bridge reuse endpoint: `/alpha-readiness/bridge-reuse.json`',
		'- This guide endpoint: `/alpha-readiness/native-host-guide.md`',
		'',
		'## UltraGear source cues to preserve',
		'',
		`- Source root: \`${nativePlatformProvenance.sourceRoot}\``,
		`- Windows Mica cues: ${nativePlatformProvenance.windowsMicaCues.map((cue) => `\`${cue}\``).join(', ')}`,
		`- macOS chrome cues: ${nativePlatformProvenance.macosChromeCues.map((cue) => `\`${cue}\``).join(', ')}`,
		`- Window action cues: ${nativePlatformProvenance.windowActionCues.map((cue) => `\`${cue}\``).join(', ')}`,
		`- Progress/report cues: ${nativePlatformProvenance.progressReportCues.map((cue) => `\`${cue}\``).join(', ')}`,
		'',
		'## Progress and report handoff mapping',
		'',
		...progressReportHandoff.statusMapping.map(
			(status) => `- \`${status.adapterState}\`: ${status.hostCue}; ${status.reportCue}`
		),
		'',
		'## Adapter boundary checklist',
		'',
		'- Do not import Tauri or native host packages into the PHP adapter runtime.',
		'- Keep real Windows 11 Mica, macOS titlebar behavior, taskbar progress, and report reveal behavior in the optional host wrapper.',
		'- Keep browser fallback history visible through `window.__SVELTEKIT_PHP_NATIVE_HOST_HISTORY__` for hosted smoke and screenshots.',
		'- Keep `set-window-effect`, `set-progress`, `clear-progress`, and `report-ready` synchronized across the live page, reports, manifest, evidence index, hosted smoke checklist, and verifier.',
		''
	];

	return lines.join('\n');
}
