import { buildBridgeReuseInventory } from './alpha-bridge-reuse';
import { buildAlphaNativeHostContract } from './alpha-native-host-contract';
import { buildAlphaNativeHostWrapperSmoke } from './alpha-native-host-wrapper-smoke';
import type { AlphaReadinessReport } from './alpha-readiness';

export function renderAlphaNativeHostGuideMarkdown(report: AlphaReadinessReport) {
	const contract = buildAlphaNativeHostContract(report);
	const bridgeReuse = buildBridgeReuseInventory(report);
	const wrapperSmoke = buildAlphaNativeHostWrapperSmoke(report);
	const runtimeBridge = contract.hostRuntimeBridge;
	const eventActions = contract.hostEvents.flatMap((event) => event.actions);
	const realHostPermissionChecklist = contract.realHostPermissionChecklist;
	const nativePlatformProvenance = bridgeReuse.nativePlatformProvenance;
	const progressReportHandoff = bridgeReuse.progressReportHandoff;
	const nativeHostWrapperProbe = contract.nativeHostWrapperProbe;
	const macosMaterialPolicy = contract.macosMaterialPolicy;
	const eventReplayContract = wrapperSmoke.eventReplayContract;
	const eventReplayTranscript = wrapperSmoke.eventReplayTranscript;
	const lines = [
		`# SvelteKit PHP ${report.target} native host binding guide`,
		'',
		`Issued: ${report.issued}`,
		`Bridge source: ${report.bridgeSource}`,
		'',
		'This guide is the alpha handoff for a Windows/macOS desktop wrapper. The PHP adapter runtime remains browser-safe: no Tauri imports, no native window calls, and no host APIs are required for hosted PHP demos.',
		'',
		'## Runtime boundary',
		'',
		`- Runtime bridge: \`${runtimeBridge.source}\``,
		`- Mounted by: \`${runtimeBridge.mountedBy}\``,
		`- Global controller: \`${runtimeBridge.globalController}\``,
		`- Global history: \`${runtimeBridge.globalHistory}\``,
		`- Result modes: ${runtimeBridge.resultModes.map((mode) => `\`${mode}\``).join(', ')}`,
		'- Hosted browser fallback records deterministic history instead of silently dropping commands.',
		'',
		'## Required host handlers',
		'',
		...runtimeBridge.handlers.map((handler) => `- \`${handler}\``),
		'',
		'## Supported `native-window-action` actions',
		'',
		...eventActions.map((action) => `- \`${action}\``),
		'',
		'## Real host permission checklist',
		'',
		`- Marker: \`${realHostPermissionChecklist.marker}\``,
		`- Source: \`${realHostPermissionChecklist.sourceRoot}/${realHostPermissionChecklist.sourceFile}\``,
		`- Trust level: \`${realHostPermissionChecklist.trustLevel}\``,
		`- Boundary: ${realHostPermissionChecklist.adapterBoundary}`,
		`- Reviewer rule: ${realHostPermissionChecklist.reviewerRule}`,
		'',
		...realHostPermissionChecklist.requiredPermissions.map(
			(item) =>
				`- \`${item.permission}\` -> actions ${item.adapterActions.map((action) => `\`${action}\``).join(', ')} -> helpers ${item.desktopShellUiHelpers.map((helper) => `\`${helper}\``).join(', ')}. ${item.proves}`
		),
		'',
		`Stable blocker: ${realHostPermissionChecklist.stableBlocker}`,
		'',
		'## macOS material policy',
		'',
		`- Marker: \`${macosMaterialPolicy.marker}\``,
		`- Trust level: \`${macosMaterialPolicy.trustLevel}\``,
		`- Host permission: \`${macosMaterialPolicy.hostPermission}\``,
		`- Source cue: ${macosMaterialPolicy.sourceCue}`,
		`- Adapter markers: ${macosMaterialPolicy.adapterMarkers.map((marker) => `\`${marker}\``).join(', ')}`,
		`- Boundary: ${macosMaterialPolicy.rendererBoundary}`,
		`- Stable blocker: ${macosMaterialPolicy.stableBlocker}`,
		'',
		'## Event detail shape',
		'',
		'```ts',
		'type NativeWindowActionDetail = {',
		"  action: 'start-dragging' | 'toggle-maximize' | 'set-window-effect' | 'set-progress' | 'clear-progress' | 'report-ready';",
		'  source?: string;',
		'  dragStartThresholdPx?: number;',
		"  windowEffect?: 'mica' | 'acrylic' | 'none';",
		'  progress?: number;',
		"  progressStatus?: 'indeterminate' | 'normal' | 'none';",
		'  reportHref?: string;',
		"  reportKind?: 'json' | 'html' | 'markdown' | 'svg' | 'csv' | 'bundle';",
		'  reportLabel?: string;',
		'};',
		'```',
		'',
		'## Browser-side registration shape',
		'',
		'```ts',
		'window.__SVELTEKIT_PHP_NATIVE_HOST__ = {',
		'  startDragging(detail) {',
		'    // Windows/macOS host starts native titlebar drag.',
		'  },',
		'  toggleMaximize(detail) {',
		'    // Host toggles maximized/restored window bounds.',
		'  },',
		'  setWindowEffect(detail) {',
		'    // Map detail.windowEffect === "mica" to Windows 11 Mica where supported.',
		'  },',
		'  setProgress(detail) {',
		'    // Map detail.progressStatus/detail.progress to taskbar or dock progress.',
		'  },',
		'  clearProgress(detail) {',
		'    // Clear taskbar or dock progress state.',
		'  },',
		'  reportReady(detail) {',
		'    // Open, reveal, copy, or badge the generated report bundle link.',
		'  }',
		'};',
		'```',
		'',
		'## LG UltraGear desktop-shell binding recipe',
		'',
		'- Source package: `packages/desktop-shell-ui/src/index.ts`.',
		'- Upstream widget source: `packages/ultragear-widget-ui/src/app.ts`.',
		'- Package name: `@scriptgpt/desktop-shell-ui`.',
		'- Reused helpers: `enableMicaWindowChrome`, `syncTaskbarProgress`, `toggleWindowMaximize`, `bindColorSchemeWatcher`, `prefersDarkMode`, and `TaskbarProgressState`.',
		'- Native cue mapping: `Effect.Mica`, `ProgressBarStatus.Indeterminate`, `ProgressBarStatus.Normal`, `ProgressBarStatus.None`, and `progress: 18`.',
		'- System appearance mapping: `prefersDarkMode` and `bindColorSchemeWatcher` wrap `window.matchMedia("(prefers-color-scheme: dark)")` for browser-safe OS theme changes.',
		'- Adapter marker: `desktopShellUiBinding` / `installSvelteKitPhpNativeHost` / `getDesktopShellUiCommandMapping` / `toDesktopShellUiTaskbarProgressState`.',
		'- Progress translation: adapter `progressStatus` maps to `TaskbarProgressState` fields `saveInFlight`, `refreshInFlight`, and `hasQueuedSave` before calling `syncTaskbarProgress`.',
		'',
		'```ts',
		"import { getCurrentWindow } from '@tauri-apps/api/window';",
		"import { bindColorSchemeWatcher, enableMicaWindowChrome, prefersDarkMode, syncTaskbarProgress, toggleWindowMaximize } from '@scriptgpt/desktop-shell-ui';",
		'',
		'export function installSvelteKitPhpNativeHost() {',
		'  const win = getCurrentWindow();',
		'  const disposeColorSchemeWatcher = bindColorSchemeWatcher(() => {',
		'    globalThis.console.info("SvelteKit PHP native shell color scheme", prefersDarkMode() ? "dark" : "light");',
		'  });',
		'',
		'  window.__SVELTEKIT_PHP_NATIVE_HOST__ = {',
		'    startDragging() {',
		'      void win.startDragging();',
		'    },',
		'    toggleMaximize() {',
		'      void toggleWindowMaximize(win);',
		'    },',
		'    setWindowEffect(detail) {',
		'      if (detail.windowEffect === "mica") void enableMicaWindowChrome(win);',
		'      // macOS wrappers keep native vibrancy/material policy host-owned; the PHP adapter only emits browser-safe material intent.',
		'    },',
		'    setProgress(detail) {',
		'      void syncTaskbarProgress(win, {',
		'        saveInFlight: detail.progressStatus === "indeterminate",',
		'        refreshInFlight: false,',
		'        hasQueuedSave: detail.progressStatus === "normal"',
		'      });',
		'    },',
		'    clearProgress() {',
		'      void syncTaskbarProgress(win, { saveInFlight: false, refreshInFlight: false, hasQueuedSave: false });',
		'    },',
		'    reportReady(detail) {',
		'      globalThis.console.info("SvelteKit PHP alpha report ready", detail.reportHref);',
		'    }',
		'  };',
		'',
		'  return disposeColorSchemeWatcher;',
		'}',
		'```',
		'',
		'The package import above belongs only in an optional Tauri/native wrapper. Do not add `@tauri-apps/api` or the UltraGear helper package to the PHP adapter runtime bundle.',
		'',
		'## Deterministic wrapper probe',
		'',
		`- Probe marker: \`${nativeHostWrapperProbe.marker}\``,
		`- Probe source: \`${nativeHostWrapperProbe.source}\``,
		`- Trust level: \`${nativeHostWrapperProbe.trustLevel}\``,
		`- Required actions: ${nativeHostWrapperProbe.requiredActions.map((action) => `\`${action}\``).join(', ')}`,
		`- Required helpers: ${nativeHostWrapperProbe.requiredHelpers.map((helper) => `\`${helper}\``).join(', ')}`,
		'',
		'Wrapper smoke steps:',
		'',
		...nativeHostWrapperProbe.steps.map(
			(step) =>
				`- \`${step.action}\` -> \`${step.expectedHandler}\` -> \`${step.desktopShellUiHelper}\`; requires \`${step.requiredHostPermission}\`; upstream \`${step.upstreamCall}\`.`
		),
		'',
		'Taskbar progress expectations:',
		'',
		...nativeHostWrapperProbe.steps
			.filter((step) => step.expectedTaskbarState)
			.map(
				(step) =>
					`- \`${step.action}\` with \`progressStatus=${step.detail.progressStatus}\`: \`saveInFlight=${step.expectedTaskbarState?.saveInFlight}\`, \`refreshInFlight=${step.expectedTaskbarState?.refreshInFlight}\`, \`hasQueuedSave=${step.expectedTaskbarState?.hasQueuedSave}\`.`
			),
		'',
		'## Deterministic event replay contract',
		'',
		`- Replay marker: \`${eventReplayContract.marker}\``,
		`- Event name: \`${eventReplayContract.eventName}\``,
		`- Controller global: \`${eventReplayContract.controllerGlobal}\``,
		`- History global: \`${eventReplayContract.historyGlobal}\``,
		`- Expected result: \`handled=${eventReplayContract.expectedHandled}\`, \`mode=${eventReplayContract.expectedMode}\``,
		`- No fallback allowed for real host: \`${eventReplayContract.noFallbackAllowedForRealHost}\``,
		`- Required result fields: ${eventReplayContract.requiredResultFields.map((field) => `\`${field}\``).join(', ')}`,
		'- Replay source: `/alpha-readiness/native-host-wrapper-smoke.json` -> `eventReplayTranscript[]`.',
		'- Acceptance rule: replay every `eventReplayTranscript[]` row, then assert every `expectedHistoryResult` records `handled=true`, `mode=native-host`, and the expected desktop-shell helper. A real wrapper must fail the smoke if history records `browser-fallback` while `noFallbackAllowedForRealHost=true`.',
		'',
		'Event replay transcript:',
		'',
		...eventReplayTranscript.map(
			(entry) =>
				`- ${entry.order}. \`${entry.marker}\`: \`${entry.action}\` -> \`${entry.expectedHandler}\` -> \`${entry.expectedDesktopShellUiHelper}\`; requires \`${entry.requiredHostPermission}\`; assert \`expectedHistoryResult.handled=${entry.expectedHistoryResult.handled}\` and \`expectedHistoryResult.mode=${entry.expectedHistoryResult.mode}\`.`
		),
		'',
		'## Live alpha proof surface',
		'',
		'- Route: `/alpha-readiness`',
		'- Status marker: `data-native-host-bridge-status`',
		'- Handoff controls marker: `data-native-host-handoff-controls`',
		'- Contract endpoint: `/alpha-readiness/native-host-contract.json`',
		'- Bridge reuse endpoint: `/alpha-readiness/bridge-reuse.json`',
		'- This guide endpoint: `/alpha-readiness/native-host-guide.md`',
		'',
		'## UltraGear source cues to preserve',
		'',
		`- Source root: \`${nativePlatformProvenance.sourceRoot}\``,
		`- Windows Mica cues: ${nativePlatformProvenance.windowsMicaCues.map((cue) => `\`${cue}\``).join(', ')}`,
		`- macOS chrome cues: ${nativePlatformProvenance.macosChromeCues.map((cue) => `\`${cue}\``).join(', ')}`,
		`- macOS material policy: \`${macosMaterialPolicy.marker}\` remains host-owned until a real macOS wrapper proves native material application.`,
		`- Window action cues: ${nativePlatformProvenance.windowActionCues.map((cue) => `\`${cue}\``).join(', ')}`,
		`- Progress/report cues: ${nativePlatformProvenance.progressReportCues.map((cue) => `\`${cue}\``).join(', ')}`,
		'',
		'## Progress and report handoff mapping',
		'',
		...progressReportHandoff.statusMapping.map(
			(status) => `- \`${status.adapterState}\`: ${status.hostCue}; ${status.reportCue}`
		),
		'',
		'## Adapter boundary checklist',
		'',
		'- Do not import Tauri or native host packages into the PHP adapter runtime.',
		'- Keep real Windows 11 Mica, macOS titlebar/vibrancy behavior, taskbar progress, and report reveal behavior in the optional host wrapper.',
		'- Keep browser fallback history visible through `window.__SVELTEKIT_PHP_NATIVE_HOST_HISTORY__` for hosted smoke and screenshots.',
		'- Keep `native-host-wrapper-event-replay`, `native-host-wrapper-event-replay-step`, `expectedHistoryResult`, `expectedDesktopShellUiHelper`, and `noFallbackAllowedForRealHost` synchronized between this guide and `/alpha-readiness/native-host-wrapper-smoke.json`.',
		'- Keep `set-window-effect`, `set-progress`, `clear-progress`, and `report-ready` synchronized across the live page, reports, manifest, evidence index, hosted smoke checklist, and verifier.',
		''
	];

	return lines.join('\n');
}
