import { buildAlphaHardProofBlockers } from './alpha-hard-proof-blockers';
import { requiredAlphaEvidence } from './alpha-required-evidence';
import { alphaTarget } from './alpha-readiness';

export function renderAlphaReleaseChecklistMarkdown() {
	const hardProofBlockers = buildAlphaHardProofBlockers();
	const lines = [
		'# SvelteKit PHP 1.0.2-alpha release checklist',
		'',
		`Candidate: \`${alphaTarget}\``,
		'',
		'This checklist defines the project-specific `1.0.2-alpha` bar. In this repo, `1.0.2-alpha` is the required pre-stable release track and is treated as above any RC label for project planning. This is a project policy, not generic SemVer prerelease ordering.',
		'',
		'## Required evidence markers',
		'',
		...requiredAlphaEvidence.map((marker) => `- \`${marker}\``),
		'',
		'## Proof status summary',
		'',
		'- `alpha-over-rc-release-policy`: source-level alpha policy evidence is present; RC/latest/stable labels remain blocked.',
		'- `csr-disabled-prerender-contract`: source-level no-hydration fixture evidence is present; hosted proof still must confirm the deployed HTML has no hydration scripts.',
		'- `latest-sveltekit-compatibility-audit`: official Svelte/SvelteKit docs and npm latest package boundaries are recorded; `latest-vite-major-validation` covers Vite 8 and vite-plugin-svelte 7 as an isolated lane, not an alpha support-floor claim.',
		'- `remote-functions-alpha-policy`: SvelteKit remote functions are explicitly blocked until generated HTTP endpoint routing has PHP fixture and hosted proof.',
		'- `native-host-wrapper-smoke`: deterministic wrapper replay evidence is present; `realHostVerified` must stay false until a real Windows/macOS wrapper run exists.',
		'- `real-host-permission-checklist`: LG UltraGear/Tauri capability cues are present; real OS-native Mica/taskbar/drag/maximize claims still require wrapper permission proof.',
		'- `native-host-compatibility-matrix`: source-observed UltraGear Windows Mica/taskbar/drag/maximize cues, including `ShellFeatureProbe.mica_supported`, `current_shell_features()`, `windowChromeState`, `webview.setBackgroundColor([0, 0, 0, 0])`, and transparent webview markers `data-window-chrome-state` / `data-transparent-webview-material-boundary`, are mapped to browser-safe host actions; this is not a real OS-native proof substitute.',
		'- `hosted-php-smoke-proof`: alpha hosted proof is present when `report/alpha-remote-smoke.json` has `status=passed`; stable still requires a fresh hosted gate for the release deployment target.',
		'',
		'## Hard proof blockers',
		'',
		'These `hardProofBlockers` rows are the `hard-proof-blocker-ledger` and feed `stablePromotionBlockers`. They intentionally separate alpha review evidence from proof required before stable `1.0.0`, real native-host claims, or fresh community claims.',
		'',
		...hardProofBlockers.flatMap((blocker) => [
			`### ${blocker.id}`,
			'',
			`- Marker: \`${blocker.marker}\``,
			`- Status: \`${blocker.status}\``,
			`- Scope: \`${blocker.scope}\``,
			`- Required command: \`${blocker.requiredCommand}\``,
			`- Required environment: ${
				blocker.requiredEnvironment?.map((name) => `\`${name}\``).join(', ') ?? '`none`'
			}`,
			`- Required artifacts: ${blocker.requiredArtifacts.map((artifact) => `\`${artifact}\``).join(', ')}`,
			`- Blocks: \`${blocker.blocks}\``,
			`- Reviewer action: ${blocker.reviewerAction}`,
			''
		]),
		'## Local alpha gate',
		'',
		'```powershell',
		'bun run alpha:report:full',
		'bun run alpha:native:smoke',
		'bun run verify:alpha',
		'bun run verify:release-prep',
		'bun run alpha:gate',
		'```',
		'',
		'The local gate must regenerate reports, verify release-prep safety, rebuild the adapter, run strict artifact sync, run unit/runtime checks, run the consumer smoke, and run the native wrapper smoke handoff.',
		'',
		'## Latest Svelte/SvelteKit compatibility audit',
		'',
		'- Audit artifact: `docs/ALPHA-LATEST-SVELTEKIT-AUDIT.md`',
		'- Source docs: SvelteKit adapter, build, page-option, project-type, Svelte 5 migration, and browser-support guidance',
		'- npm latest snapshot: `svelte@5.56.4`, `@sveltejs/kit@2.69.1`, `@sveltejs/vite-plugin-svelte@7.1.4`, and `vite@8.1.3`',
		'- Freshness verifier: `bun run verify:latest-sveltekit-audit` compares this source-controlled snapshot with current `npm view` output',
		'- Same-major smoke: `bun run alpha:latest-same-major:smoke` packs this adapter, installs it into a temporary fixture with npm-latest `svelte@5.x` and `@sveltejs/kit@2.x`, runs `vite build`, and checks generated PHP/static output',
		'- Current alpha support floor: same-major `svelte` and `@sveltejs/kit` compatibility is a local-gate proof lane, not an in-place dependency-floor upgrade',
		'- Vite-major smoke: `bun run alpha:latest-vite-major:smoke` validates `vite@8` and `@sveltejs/vite-plugin-svelte@7` in an isolated packed fixture before dependency floors move',
		'- Stable blocker: add explicit proof or an unsupported-feature policy for newer SvelteKit server surfaces such as remote functions',
		'',
		'## Remote functions alpha policy',
		'',
		'- Policy artifact: `docs/REMOTE-FUNCTIONS-ALPHA-POLICY.md`',
		'- Required marker: `remote-functions-alpha-policy`',
		'- Current status: unsupported in PHP runtime alpha output',
		'- Guarded config: `kit.experimental.remoteFunctions` must stay disabled',
		'- Guarded files: `.remote.js`, `.remote.ts`, `.remote.mjs`, `.remote.mts`, `.remote.cjs`, and `.remote.cts`',
		'- Platform signal: `event.platform.php.remoteFunctions.supported` reports `false`',
		'- Verifier: `bun run verify:remote-functions`',
		'- Promotion rule: generated remote-function HTTP endpoints need PHP router fixture proof and hosted PHP smoke proof before support can be claimed',
		'',
		'## Hosted alpha gate',
		'',
		'```powershell',
		'$env:ALPHA_SMOKE_BASE_URL = "https://example.com"',
		'bun run alpha:gate:hosted',
		'```',
		'',
		'Guarded dev-host proof lane:',
		'',
		'```powershell',
		'$env:DEPLOY_REMOTE = "domains/blog.canopydigital.ca/public_html/dev/sveltekitphp"',
		'$env:DEPLOY_IDENTITY_FILE = "$HOME\\.ssh\\id_ed25519_ryanspice"',
		'$env:ALPHA_SMOKE_BASE_URL = "https://blog.canopydigital.ca/dev/sveltekitphp/"',
		'bun run alpha:deploy:dev-host -- --apply --smoke',
		'```',
		'',
		'- `alpha:deploy:dev-host` builds with `SK_BASE_PATH=/dev/sveltekitphp` and `DEPLOY_BASE=/dev/sveltekitphp`.',
		'- The command refuses broad remote paths and requires `DEPLOY_REMOTE` to end with `/dev/sveltekitphp` before upload.',
		'- Use this lane for Canopy dev proof only; production deploys stay outside the alpha hosted proof workflow.',
		'',
		'`ALPHA_SMOKE_BASE_URL` must be an HTTP(S) origin/path without credentials or query tokens. Hosted smoke is not pass evidence until it targets a real deployed PHP host.',
		'',
		'## Native shell evidence',
		'',
		'- Reuse cue package: `@scriptgpt/desktop-shell-ui`',
		'- Source cue: `packages/desktop-shell-ui/src/index.ts`',
		'- Widget cue: `packages/ultragear-widget-ui/src/app.ts`',
		'- Capability cue: `src-tauri/capabilities/default.json`',
		'- Permission checklist marker: `lg-ultragear-host-permission-checklist`',
		'- Runtime checklist field: `realHostPermissionChecklist`',
		'- Host handler permission field: `requiredHostPermission`',
		'- Host global: `window.__SVELTEKIT_PHP_NATIVE_HOST__`',
		'- Wrapper smoke command: `bun run alpha:native:smoke`',
		'- Wrapper smoke endpoint/artifact: `/alpha-readiness/native-host-wrapper-smoke.json` and `report/alpha-native-host-wrapper-smoke.json`',
		'- Wrapper smoke marker: `native-host-wrapper-smoke` (deterministic handoff only; real host smoke stays host-owned)',
		'- Wrapper smoke boundary markers: `deterministic-host-wrapper-handoff`, `native-host-wrapper-event-replay`, `expectedHistoryResult`, `expectedDesktopShellUiHelper`, `noFallbackAllowedForRealHost`, `realHostVerified: false`, and `noNativeApiBoundary`',
		'- System appearance helpers: `prefersDarkMode`, `bindColorSchemeWatcher`, and `window.matchMedia("(prefers-color-scheme: dark)")`',
		'- Installer marker: `installSvelteKitPhpNativeHost`',
		'- Mapping marker: `getDesktopShellUiCommandMapping`',
		'- Progress translation marker: `toDesktopShellUiTaskbarProgressState`',
		'',
		'Required action-to-helper mapping:',
		'',
		'- `start-dragging` -> `win.startDragging()`; requires `core:window:allow-start-dragging`',
		'- `toggle-maximize` -> `toggleWindowMaximize(win)`; requires `core:window:allow-toggle-maximize`',
		'- `set-window-effect` -> `enableMicaWindowChrome(win)`; requires `core:window:allow-set-effects`',
		'- Chrome-state/transparency boundary markers: `windowChromeState`, `mica-active`, `mica-inactive`, `plain`, `webview.setBackgroundColor([0, 0, 0, 0])`, `data-window-chrome-state`, `data-window-chrome-state="mica-active"`, `data-transparent-webview-material-boundary`, and `data-transparent-webview-material-boundary="host-owned"` are alpha evidence markers only; real transparent webview and Mica execution remain host-owned.',
		'- system appearance -> `bindColorSchemeWatcher(() => prefersDarkMode())`',
		'- `set-progress` -> `syncTaskbarProgress(win, { saveInFlight: progressStatus === "indeterminate", refreshInFlight: false, hasQueuedSave: progressStatus === "normal" })`; requires `core:window:allow-set-progress-bar`',
		'- `clear-progress` -> `syncTaskbarProgress(win, { saveInFlight: false, refreshInFlight: false, hasQueuedSave: false })`; requires `core:window:allow-set-progress-bar`',
		'- `report-ready` -> `host.reportReady(...)`',
		'',
		'Real-host promotion rule: CSS/DOM/native-shell visual markers are not enough. A wrapper must prove the required host permissions above before Mica, taskbar progress, drag, maximize, or focus behavior can be described as real OS-native execution.',
		'',
		'The PHP adapter must remain browser/PHP-host safe. Tauri APIs belong only in an optional native wrapper.',
		'',
		'## No-hydration prerender evidence',
		'',
		'- Fixture route: `/alpha-readiness/no-hydration`',
		'- Route config: `prerender=true` and `csr=false`',
		'- Required markers: `no-hydration-fixture`, `csr-disabled-prerender-contract`, and `theme-stable-ssr-html`',
		'- Forbidden hosted markers: `<script`, `sveltekit:start`, and `data-sveltekit-hydrate`',
		'- Release use: catches blog/static-theme regressions where a prerendered shell renders the right theme first, then client hydration repaints it after load.',
		'',
		'## Community analytics evidence',
		'',
		'- `sourceToKeywordEdge`',
		'- `analyticsLinkageMarker`',
		'- `weightedDemandScore`',
		'- `freshnessMaxAgeHours`',
		'- `trustBoundary`',
		'- `manualReviewRequired`',
		'- `result-total-field-contract`',
		'- `top-result-field-contract`',
		'- `sample-review-rule`',
		'- `resultTotalField`',
		'- `topResultFields`',
		'- `sampleReviewRule`',
		'- `weighted_demand_score`',
		'- `source_to_keyword_edges`',
		'- `source_to_keyword_edge`',
		'- `result_total_field`',
		'- `top_result_fields`',
		'- `sample_review_rule`',
		'',
		'Source-field contract: `result-total-field-contract`, `top-result-field-contract`, and `sample-review-rule` must stay visible in the research pack and source map, with `result_total_field`, `top_result_fields`, and `sample_review_rule` present in `report/alpha-community-sources.csv`.',
		'',
		'Community counts are directional public-source signals, not telemetry and not release claims by themselves.',
		'',
		'## Runtime and artifact safety',
		'',
		'- root `router.php` delegates to generated runtime routing',
		'- generated routers reject traversal, encoded separators, control/null bytes, and protected paths',
		'- `/alpha-readiness/no-hydration` stays `prerender=true` and `csr=false`, with hosted smoke rejecting client script/hydration markers',
		'- checked-in `adapter/index.js` is synchronized with source',
		'- `event.platform.php` exposes adapter mode/runtime capability flags through SvelteKit `emulate().platform` without secrets',
		'- `docs/ALPHA-LATEST-SVELTEKIT-AUDIT.md` tracks latest Svelte/SvelteKit docs, package boundaries, remote-function risk, and Vite/plugin validation lanes',
		'- `verify:latest-sveltekit-audit` fails when the source-controlled npm latest snapshot drifts from current registry output',
		'- `alpha:latest-same-major:smoke` fails when npm-latest Svelte 5 or SvelteKit 2 can no longer build a minimal PHP/static adapter fixture',
		'- `docs/REMOTE-FUNCTIONS-ALPHA-POLICY.md` and `verify:remote-functions` keep remote-functions support blocked until generated endpoint routing is proven',
		'- deploy and hosted smoke commands fail on empty, placeholder, or unsafe environment values',
		'',
		'## Stable blocker',
		'',
		'Stable `1.0.2` remains blocked until the current full local gate, strict artifact sync, packed consumer proof, fresh hosted PHP smoke for the release deployment target, newer Kit server-surface proof or unsupported-feature policy, real native-host proof for OS-native claims, and regenerated required alpha evidence are all current.',
		''
	];

	return lines.join('\n');
}

