export function getRouterSharedPhp(base: string) {
	return `<?php
// Simple router to emulate Apache .htaccess mod_rewrite
// for the PHP built-in server.
// Generated by @ryanspice/sveltekit-adapter-php

require_once __DIR__ . '/_runtime/compat.php';

$path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH);
if (!is_string($path) || $path === '') $path = '/';
$path = preg_replace('#/+#', '/', $path);
$uri_raw = rawurldecode($path);
$uri_raw = str_replace('\\\\', '/', $uri_raw);
$base_env = getenv('SK_BASE_PATH');
$base = $base_env !== false ? $base_env : '${base}';
if ($base === '/' || $base === '.') $base = '';
if ($base !== '' && $base[0] !== '/') $base = '/' . $base;
$base = rtrim($base, '/');
$uri = $uri_raw;

if (!function_exists('router_debug_enabled')) {
    function router_debug_enabled() {
        $value = getenv('SK_DEBUG');
        if ($value === false) $value = getenv('ADAPTER_DEBUG');
        if ($value === false) return false;
        return in_array(strtolower((string)$value), ['1', 'true', 'yes', 'on'], true);
    }
}

if (!function_exists('router_log')) {
    function router_log($msg) {
        if (!router_debug_enabled()) return;
        file_put_contents('php://stderr', "[Router] ".$msg. "\\n", FILE_APPEND);
    }
}

if (!function_exists('router_has_bad_path')) {
    function router_has_bad_path($path) {
        $decoded = (string)$path;
        for ($i = 0; $i < 3; $i++) {
            $next = rawurldecode($decoded);
            if ($next === $decoded) break;
            $decoded = $next;
        }
        if (preg_match('/[\\x00-\\x1f\\x7f]/', $decoded)) return true;
        $decoded = str_replace('\\\\', '/', $decoded);
        foreach (explode('/', $decoded) as $segment) {
            if ($segment === '..' || $segment === '.') return true;
        }
        return false;
    }
}

if (!function_exists('router_safe_path')) {
    function router_safe_path($root, $candidate) {
        if (!is_string($candidate) || $candidate === '') return null;
        $rootReal = realpath($root);
        if ($rootReal === false) return null;
        $real = realpath($candidate);
        if ($real === false) return null;

        $rootNorm = rtrim(str_replace('\\\\', '/', $rootReal), '/');
        $realNorm = str_replace('\\\\', '/', $real);
        if ($realNorm !== $rootNorm && strpos($realNorm, $rootNorm . '/') !== 0) {
            return null;
        }
        return $real;
    }
}

if (!function_exists('router_mime_type')) {
    function router_mime_type($path) {
        $ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));
        $mimes = [
            'js' => 'application/javascript',
            'mjs' => 'application/javascript',
            'cjs' => 'application/javascript',
            'css' => 'text/css',
            'json' => 'application/json',
            'html' => 'text/html',
            'htm' => 'text/html',
            'xml' => 'text/xml',
            'txt' => 'text/plain',
            'svg' => 'image/svg+xml',
            'png' => 'image/png',
            'jpg' => 'image/jpeg',
            'jpeg' => 'image/jpeg',
            'gif' => 'image/gif',
            'webp' => 'image/webp',
            'ico' => 'image/x-icon',
            'woff2' => 'font/woff2',
            'woff' => 'font/woff',
            'ttf' => 'font/ttf',
            'eot' => 'application/vnd.ms-fontobject'
        ];
        return $mimes[$ext] ?? (function_exists('mime_content_type') ? mime_content_type($path) : 'application/octet-stream');
    }
}

if (!function_exists('router_send_file')) {
    function router_send_file($path, $mime = null) {
        $file = router_safe_path(__DIR__, $path);
        if ($file === null || !is_file($file)) {
            http_response_code(404);
            return false;
        }

        $mime = $mime ?? router_mime_type($file);
        header('Content-Type: '.$mime);
        header('Content-Length: '.filesize($file));
        if (($_SERVER['REQUEST_METHOD'] ?? 'GET') !== 'HEAD') {
            readfile($file);
        }
        return true;
    }
}

if (router_has_bad_path($path) || router_has_bad_path($uri_raw)) {
	http_response_code(400);
	echo "Bad Request";
	return;
}

if (preg_match('#(^|/)_protected(?:/|$)#', $uri_raw)) {
	http_response_code(403);
	echo "Access Denied";
	return;
}

$file = router_safe_path(__DIR__, __DIR__ . $uri_raw);
if ($uri_raw !== '/' && $file !== null && is_file($file)) {
	return false;
}

// Router Runtime Hardening
if (!defined('SK_ROUTER_HARDENED')) {
    define('SK_ROUTER_HARDENED', 1);

    ob_start();
    ini_set('display_errors', '0');
    ini_set('log_errors', '1');
    ini_set('error_log', 'php://stderr');
    error_reporting(E_ALL);

    set_error_handler(function($severity, $message, $file, $line) {
        if (!(error_reporting() & $severity)) {
            return false;
        }
        error_log("[php-warning] $message in $file:$line");
        return true; // Don't execute PHP internal error handler
    });
}

router_log("Request path: " . (parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/'));
router_log("Base Env: '$base_env'");
router_log("Base Used: '$base'");

if ($base !== '' && ($uri === '/' || $uri === '')) {
    $target = $base . '/';
    $q = $_SERVER['QUERY_STRING'] ?? '';
    if ($q !== '') {
        $target .= '?' . $q;
    }
    header("Location: $target", true, 308);
    http_response_code(308);
    return;
}

if ($base !== '' && $uri !== $base && strpos($uri, $base . '/') !== 0) {
	http_response_code(404);
	echo "404 Not Found";
	return;
}

if (preg_match('#^/_protected(?:/|$)#', $uri) || ($base !== '' && preg_match('#^' . preg_quote($base, '#') . '/_protected(?:/|$)#', $uri))) {
	http_response_code(403);
    echo "Access Denied";
	return;
}
`;
}
