export function getRouterSharedPhp(base: string) {
	return `<?php
// Simple router to emulate Apache .htaccess mod_rewrite
// for the PHP built-in server.
// Generated by @ryanspice/sveltekit-adapter-php

require_once __DIR__ . '/_runtime/compat.php';

$path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$uri_raw = urldecode(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH));
$base_env = getenv('SK_BASE_PATH');
$base = $base_env !== false ? $base_env : '${base}';
$uri = $uri_raw;

if (strpos($path, '/../') !== false || strpos($path, '/..\\\\') !== false) {
	http_response_code(400);
	echo "Bad Request";
	return;
}

if (strpos($path, '/_protected/') !== false) {
	http_response_code(403);
	echo "Access Denied";
	return;
}

$file = __DIR__ . $path;
if ($path !== '/' && is_file($file)) {
	return false;
}

// Router Runtime Hardening
if (!defined('SK_ROUTER_HARDENED')) {
    define('SK_ROUTER_HARDENED', 1);

    ob_start();
    ini_set('display_errors', '0');
    ini_set('log_errors', '1');
    ini_set('error_log', 'php://stderr');
    error_reporting(E_ALL);

    set_error_handler(function($severity, $message, $file, $line) {
        if (!(error_reporting() & $severity)) {
            return false;
        }
        error_log("[php-warning] $message in $file:$line");
        return true; // Don't execute PHP internal error handler
    });
}

if (!function_exists('router_log')) {
    function router_log($msg) {
        file_put_contents(__DIR__ . '/../router.log', "[Router] ".$msg. "\n", FILE_APPEND);
    }
}

router_log("Request: $uri");
router_log("Base Env: '$base_env'");
router_log("Base Used: '$base'");

if ($base !== '' && ($uri === '/' || $uri === '')) {
    $target = $base . '/';
    $q = $_SERVER['QUERY_STRING'] ?? '';
    if ($q !== '') {
        $target .= '?' . $q;
    }
    header("Location: $target", true, 308);
    http_response_code(308);
    return;
}

if (strpos($uri, '/_protected/') === 0 || ($base !== '' && strpos($uri, $base . '/_protected/') === 0)) {
	http_response_code(403);
    echo "Access Denied";
	return;
}
`;
}
