export function getRouterSharedPhp(base: string) {
	return `<?php
// Simple router to emulate Apache .htaccess mod_rewrite
// for the PHP built-in server.
// Generated by @ryanspice/sveltekit-adapter-php

require_once __DIR__ . '/_runtime/compat.php';

$path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH);
if (!is_string($path) || $path === '') $path = '/';
$path = preg_replace('#/+#', '/', $path);
$uri_raw = rawurldecode($path);
$uri_raw = str_replace('\\\\', '/', $uri_raw);
$base_env = getenv('SK_BASE_PATH');
$base = $base_env !== false ? $base_env : '${base}';
if ($base === '/' || $base === '.') $base = '';
if ($base !== '' && $base[0] !== '/') $base = '/' . $base;
$base = rtrim($base, '/');
$uri = $uri_raw;

if (!function_exists('router_debug_enabled')) {
    function router_debug_enabled() {
        $value = getenv('SK_DEBUG');
        if ($value === false) $value = getenv('ADAPTER_DEBUG');
        if ($value === false) return false;
        return in_array(strtolower((string)$value), ['1', 'true', 'yes', 'on'], true);
    }
}

if (!function_exists('router_log')) {
    function router_log($msg) {
        if (!router_debug_enabled()) return;
        file_put_contents('php://stderr', "[Router] ".$msg. "\\n", FILE_APPEND);
    }
}

if (!function_exists('router_has_bad_path')) {
    function router_has_bad_path($path) {
        $decoded = (string)$path;
        for ($i = 0; $i < 3; $i++) {
            $next = rawurldecode($decoded);
            if ($next === $decoded) break;
            $decoded = $next;
        }
        $decoded = str_replace('\\\\', '/', $decoded);
        foreach (explode('/', $decoded) as $segment) {
            if ($segment === '..') return true;
        }
        return false;
    }
}

if (!function_exists('router_safe_path')) {
    function router_safe_path($root, $candidate) {
        if (!is_string($candidate) || $candidate === '') return null;
        $rootReal = realpath($root);
        if ($rootReal === false) return null;
        $real = realpath($candidate);
        if ($real === false) return null;

        $rootNorm = rtrim(str_replace('\\\\', '/', $rootReal), '/');
        $realNorm = str_replace('\\\\', '/', $real);
        if ($realNorm !== $rootNorm && strpos($realNorm, $rootNorm . '/') !== 0) {
            return null;
        }
        return $real;
    }
}

if (router_has_bad_path($path) || router_has_bad_path($uri_raw)) {
	http_response_code(400);
	echo "Bad Request";
	return;
}

if (strpos($uri_raw, '/_protected/') !== false) {
	http_response_code(403);
	echo "Access Denied";
	return;
}

$file = router_safe_path(__DIR__, __DIR__ . $uri_raw);
if ($uri_raw !== '/' && $file !== null && is_file($file)) {
	return false;
}

// Router Runtime Hardening
if (!defined('SK_ROUTER_HARDENED')) {
    define('SK_ROUTER_HARDENED', 1);

    ob_start();
    ini_set('display_errors', '0');
    ini_set('log_errors', '1');
    ini_set('error_log', 'php://stderr');
    error_reporting(E_ALL);

    set_error_handler(function($severity, $message, $file, $line) {
        if (!(error_reporting() & $severity)) {
            return false;
        }
        error_log("[php-warning] $message in $file:$line");
        return true; // Don't execute PHP internal error handler
    });
}

router_log("Request path: " . (parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/'));
router_log("Base Env: '$base_env'");
router_log("Base Used: '$base'");

if ($base !== '' && ($uri === '/' || $uri === '')) {
    $target = $base . '/';
    $q = $_SERVER['QUERY_STRING'] ?? '';
    if ($q !== '') {
        $target .= '?' . $q;
    }
    header("Location: $target", true, 308);
    http_response_code(308);
    return;
}

if (strpos($uri, '/_protected/') === 0 || ($base !== '' && strpos($uri, $base . '/_protected/') === 0)) {
	http_response_code(403);
    echo "Access Denied";
	return;
}
`;
}
