<?php
// Simple router to emulate Apache .htaccess mod_rewrite
// for the PHP built-in server.
// Generated by @ryanspice/sveltekit-adapter-php

require_once __DIR__ . '/_runtime/compat.php';

$path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$uri_raw = urldecode(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH));
$base_env = getenv('SK_BASE_PATH');
$base = $base_env !== false ? $base_env : '';
$uri = $uri_raw;

if (strpos($path, '/../') !== false || strpos($path, '/..\\') !== false) {
	http_response_code(400);
	echo "Bad Request";
	return;
}

if (strpos($path, '/_protected/') !== false) {
	http_response_code(403);
	echo "Access Denied";
	return;
}

$file = __DIR__ . $path;
if ($path !== '/' && is_file($file)) {
	return false;
}

// Router Runtime Hardening
if (!defined('SK_ROUTER_HARDENED')) {
    define('SK_ROUTER_HARDENED', 1);

    ob_start();
    ini_set('display_errors', '0');
    ini_set('log_errors', '1');
    ini_set('error_log', 'php://stderr');
    error_reporting(E_ALL);

    set_error_handler(function($severity, $message, $file, $line) {
        if (!(error_reporting() & $severity)) {
            return false;
        }
        error_log("[php-warning] $message in $file:$line");
        return true; // Don't execute PHP internal error handler
    });
}

if (!function_exists('router_log')) {
    function router_log($msg) {
        file_put_contents(__DIR__ . '/../router.log', "[Router] ".$msg. "
", FILE_APPEND);
    }
}

router_log("Request: $uri");
router_log("Base Env: '$base_env'");
router_log("Base Used: '$base'");

if ($base !== '' && ($uri === '/' || $uri === '')) {
    $target = $base . '/';
    $q = $_SERVER['QUERY_STRING'] ?? '';
    if ($q !== '') {
        $target .= '?' . $q;
    }
    header("Location: $target", true, 308);
    http_response_code(308);
    return;
}

if (strpos($uri, '/_protected/') === 0 || ($base !== '' && strpos($uri, $base . '/_protected/') === 0)) {
	http_response_code(403);
    echo "Access Denied";
	return;
}

$path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
if (strpos($path, '/../') !== false || strpos($path, '/..\') !== false) {
	http_response_code(400);
	echo "Bad Request";
	return;
}

// 0. Try to serve exact file match; preserves base path nesting
$full_path = __DIR__ . $uri;
if ($uri !== '/' && file_exists($full_path)) {
	if (is_file($full_path)) {
		$real = realpath($full_path);
		if ($real === false || strpos($real, realpath(__DIR__)) !== 0) {
			http_response_code(403);
			return;
		}

/* deleted block */
	} elseif (is_dir($full_path)) {
		// If accessing directory, check for index
		foreach (array('/index.php', '/index.html') as $idx) {
			$candidate = $full_path . $idx;
			if (is_file($candidate)) {
                if (substr($uri, -1) !== '/') {
					// Redirect to slash
					$target = $uri . '/';
					if (isset($_SERVER['QUERY_STRING']) && $_SERVER['QUERY_STRING'] !== '') {
						$target .= '?' . $_SERVER['QUERY_STRING'];
					}
					header("Location: $target", true, 301);
					return;
				}

				if (substr($candidate, -4) === '.php') {
					$_SERVER['SCRIPT_FILENAME'] = realpath($candidate);
					require $candidate;
					return;
				}
				header('Content-Type: text/html; charset=utf-8');
				readfile($candidate);
				return;
			}
		}
	}
}

if ($base !== '' && strpos($uri, $base) === 0) {
    $uri = substr($uri, strlen($base));
    if ($uri === '' || $uri === false) $uri = '/';
}
if (strlen($uri) > 0 && $uri[0] !== '/') {
    $uri = '/' . $uri;
}
$path = __DIR__ . $uri;
if ($uri !== '/' && is_dir($path)) {
    foreach (['/index.html', '/index.php'] as $idx) {
        $candidate = $path . $idx;
        if (is_file($candidate)) {
            if (substr($candidate, -4) === '.php') {
                $requested_file = realpath($candidate);
                if ($requested_file) {
                    $_SERVER['SCRIPT_FILENAME'] = $requested_file;
                    require $requested_file;
                    return;
                }
            }
            header('Content-Type: text/html; charset=utf-8');
            readfile($candidate);
            return;
        }
    }
}
if (file_exists($path) && is_file($path)) {
    $real = realpath($path);
    if ($real === false || strpos($real, realpath(__DIR__)) !== 0) {
        http_response_code(403);
        return;
    }

    $ext = pathinfo($path, PATHINFO_EXTENSION);
    $mimes = [];
		$mimes['js'] = 'application/javascript';
		$mimes['css'] = 'text/css';
		$mimes['html'] = 'text/html';
		$mimes['json'] = 'application/json';
		$mimes['png'] = 'image/png';
		$mimes['jpg'] = 'image/jpeg';
		$mimes['svg'] = 'image/svg+xml';
		$mimes['ico'] = 'image/x-icon';
		$mimes['txt'] = 'text/plain';
		$mimes['xml'] = 'text/xml';
    $mime = $mimes[$ext] ?? 'application/octet-stream';
    header('Content-Type: '.$mime);
    readfile($path);
    return;
}

?>
