import path from 'node:path';
import { writeFile, mkdir } from 'node:fs/promises';
import type { AdapterOptions, Builder } from './types.js';

/**
 * Production-ready Apache deployment adapter
 * Generates .htaccess files and optimized PHP for Apache servers
 */
export default function sveltekitApacheAdapter(options: AdapterOptions = {}) {
	const {
		ssr = true,
		out = './build',
		assets = './build',
		precompress = false,
		strict = true
	} = options;

	return {
		name: '@ryanspice/sveltekit-adapter-php-apache',
		async adapt(builder: Builder) {
			const outDir = path.resolve(out);
			const assetsDir = path.resolve(assets);

			builder.log.minor('🚀 Apache adapter - production deployment');

			// 1) Client assets
			builder.log.minor('Writing client assets');
			const writtenClientFiles = builder.writeClient(assetsDir);

			// 2) Server-side rendering
			if (ssr) {
				builder.log.minor('Writing server-side rendering files');
				const writtenServerFiles = builder.writeServer(outDir);

				// Generate Apache-specific .htaccess
				const htaccess = generateHtaccess(strict);
				await writeFile(path.join(outDir, '.htaccess'), htaccess, 'utf8');
				builder.log.minor('Created Apache .htaccess file');

				// Generate Apache-optimized PHP bootstrap
				const bootstrap = generateApacheBootstrap();
				await writeFile(path.join(outDir, 'index.php'), bootstrap, 'utf8');
				builder.log.minor('Created Apache-optimized PHP bootstrap');
			}

			// 3) Static assets
			builder.log.minor('Writing static assets');
			const writtenStaticFiles = builder.writeStatic(assetsDir);

			// 4) Generate Apache deployment instructions
			const deploymentGuide = generateDeploymentGuide(outDir);
			await writeFile(path.join(outDir, 'APACHE_DEPLOYMENT.md'), deploymentGuide, 'utf8');
			builder.log.minor('Created Apache deployment guide');

			const totalFiles = writtenClientFiles + (writtenServerFiles || 0) + writtenStaticFiles;
			builder.log.success(`✅ Apache adapter complete - ${totalFiles} files ready for deployment`);
		}
	};
}

function generateHtaccess(strict: boolean): string {
	return `# Apache configuration for SvelteKit PHP adapter
# Generated by @ryanspice/sveltekit-adapter-php-apache

# Enable rewrite engine
RewriteEngine On

# Handle client-side routing
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [QSA,L]

# Security headers
Header always set X-Content-Type-Options nosniff
Header always set X-Frame-Options DENY
Header always set X-XSS-Protection "1; mode=block"

# Compression
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/json
</IfModule>

# Cache control for static assets
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/gif "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType text/css "access plus 1 month"
    ExpiresByType application/javascript "access plus 1 month"
    ExpiresByType application/json "access plus 1 hour"
</IfModule>

${strict ? '# Strict mode - no directory listing\nOptions -Indexes' : '# Directory listing allowed in non-strict mode'}

# PHP settings
php_flag display_errors Off
php_flag log_errors On
php_value error_log error.log
`;
}

function generateApacheBootstrap(): string {
	return `<?php
/**
 * Apache-optimized SvelteKit PHP bootstrap
 * Handles routing and SSR for Apache deployment
 */

// Error handling
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

// Get request URI
$uri = $_SERVER['REQUEST_URI'] ?? '/';
$path = parse_url($uri, PHP_URL_PATH);

// Remove trailing slash for consistency
$path = rtrim($path, '/') ?: '/';

// Handle static files directly
if (file_exists(__DIR__ . $path) && is_file(__DIR__ . $path)) {
    return false; // Let Apache serve the file
}

// Handle PHP files
if (file_exists(__DIR__ . $path . '.php')) {
    include __DIR__ . $path . '.php';
    return;
}

// Handle directories with index.php
if (file_exists(__DIR__ . $path . '/index.php')) {
    include __DIR__ . $path . '/index.php';
    return;
}

// Main application routing
$indexFile = __DIR__ . '/index.html';
if (file_exists($indexFile)) {
    // Serve the main application
    include $indexFile;
    return;
}

// 404 fallback
http_response_code(404);
echo '<h1>404 Not Found</h1>';
echo '<p>The requested page could not be found.</p>';
echo '<hr><small>SvelteKit Apache Adapter</small>';
?>`;
}

function generateDeploymentGuide(outDir: string): string {
	return `# Apache Deployment Guide

## Prerequisites
- Apache 2.4+ with mod_rewrite enabled
- PHP 8.0+ with required extensions
- mod_deflate and mod_expires (optional but recommended)

## Installation Steps

1. **Upload Files**
   Upload all files from the \`${outDir}\` directory to your Apache document root (e.g., \`/var/www/html\`)

2. **Enable Required Apache Modules**
   \`\`\`bash
   sudo a2enmod rewrite
   sudo a2enmod deflate
   sudo a2enmod expires
   sudo a2enmod headers
   sudo systemctl restart apache2
   \`\`\`

3. **Set Permissions**
   \`\`\`bash
   sudo chown -R www-data:www-data /var/www/html
   sudo chmod -R 755 /var/www/html
   \`\`\`

4. **Configure Virtual Host (Optional)**
   Create/edit your Apache virtual host configuration:
   \`\`\`apache
   <VirtualHost *:80>
       ServerName your-domain.com
       DocumentRoot /var/www/html
       
       <Directory /var/www/html>
           AllowOverride All
           Require all granted
       </Directory>
   </VirtualHost>
   \`\`\`

## Testing

1. **Check .htaccess**: Visit \`http://your-domain.com/test\` - should redirect to index.php
2. **Check PHP**: Create a \`phpinfo.php\` file to verify PHP is working
3. **Check SSR**: Navigate to different routes to ensure server-side rendering works

## Troubleshooting

### Common Issues

1. **404 errors on routes**: Ensure mod_rewrite is enabled and .htaccess is readable
2. **PHP files not executing**: Check PHP installation and file permissions
3. **Static assets not loading**: Verify Apache can read the asset files
4. **Slow performance**: Enable mod_deflate and mod_expires

### Debug Mode

Add \`?debug=1\` to any URL to enable debug output.

## Security Considerations

- Keep your PHP version updated
- Use HTTPS in production
- Configure proper file permissions
- Consider implementing rate limiting
- Enable security headers in .htaccess

## Performance Optimization

- Enable OPcache for PHP
- Use a CDN for static assets
- Configure proper caching headers
- Consider using Apache's mod_cache
`;
}