import path from 'node:path';
import { writeFile } from 'node:fs/promises';
import type { AdapterOptions, Builder } from './types.js';

/**
 * Production-ready Apache deployment adapter
 * Generates .htaccess files and optimized PHP for Apache servers
 */
export default function sveltekitApacheAdapter(options: AdapterOptions = {}) {
	const { ssr = true, out = './build', assets = './build', strict = true } = options;

	return {
		name: '@ryanspice/sveltekit-adapter-php-apache',
		async adapt(builder: Builder) {
			const outDir = path.resolve(out);
			const assetsDir = path.resolve(assets);
			const basePath = options.basePath ?? builder.config.kit.paths.base ?? '';

			builder.log.minor('🚀 Apache adapter - production deployment');

			// 1) Client assets
			builder.log.minor('Writing client assets');
			const writtenClientFiles = builder.writeClient(assetsDir);

			let writtenServerFiles = 0;

			// 2) Server-side rendering
			if (ssr) {
				builder.log.minor('Writing server-side rendering files');
				writtenServerFiles = builder.writeServer(outDir);

				// Generate Apache-specific .htaccess
				const htaccess = generateHtaccess(strict, basePath || '');
				await writeFile(path.join(outDir, '.htaccess'), htaccess, 'utf8');
				builder.log.minor('Created Apache .htaccess file');

				// Generate Apache-optimized PHP bootstrap
				const bootstrap = generateApacheBootstrap(basePath || '');
				await writeFile(path.join(outDir, 'index.php'), bootstrap, 'utf8');
				builder.log.minor('Created Apache-optimized PHP bootstrap');
			}

			// 3) Static assets
			builder.log.minor('Writing static assets');
			const writtenStaticFiles = builder.writeStatic(assetsDir);

			// 4) Generate Apache deployment instructions
			const deploymentGuide = generateDeploymentGuide(outDir);
			await writeFile(path.join(outDir, 'APACHE_DEPLOYMENT.md'), deploymentGuide, 'utf8');
			builder.log.minor('Created Apache deployment guide');

			const totalFiles = writtenClientFiles + (writtenServerFiles || 0) + writtenStaticFiles;
			builder.log.success(`✅ Apache adapter complete - ${totalFiles} files ready for deployment`);
		}
	};
}

function generateHtaccess(strict: boolean, base: string): string {
	const baseTrimmed = base.replace(/^\/+|\/+$/g, '');
	const baseOptional = baseTrimmed ? `(?:${baseTrimmed}/)?` : '';
	const basePrefix = baseTrimmed ? `${baseTrimmed}/` : '';
	return `# Apache configuration for SvelteKit PHP adapter
# Generated by @ryanspice/sveltekit-adapter-php-apache

# Enable rewrite engine
RewriteEngine On

# Trailing slash handling - align with SvelteKit's trailingSlash config
# This should match the SvelteKit kit.trailingSlash setting
# Default to 'never' (redirect to no trailing slash) for consistency with router.php
RewriteCond %{REQUEST_URI} /$
RewriteCond %{REQUEST_URI} !^${baseOptional}$
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)/$ /$1 [R=308,L]

# Block access to protected runtime files
RewriteRule ^_protected/ - [F]

RewriteRule ^${baseOptional}_app/ - [L]
RewriteRule ^${basePrefix}.+/_app/(.*)$ ${basePrefix}_app/$1 [L]
RewriteRule ^.+/_app/(.*)$ _app/$1 [L]
RewriteRule ^${baseOptional}[^?]+\\.(css|js|map|mjs|cjs|json|png|jpg|jpeg|gif|webp|svg|ico|txt|xml|woff2|woff|ttf|eot)$ - [L]

RewriteCond %{REQUEST_URI} ^/${baseTrimmed ? `${baseTrimmed}/` : ''}(.*/)?__data\\.json$
RewriteCond %{DOCUMENT_ROOT}/${baseTrimmed ? `${baseTrimmed}/` : ''}%1__data.php -f
RewriteRule ^(.*/)?__data\\.json$ $1__data.php [L]

# Serve directory index if it exists (index.php or index.html)
RewriteCond %{REQUEST_FILENAME} -d
RewriteCond %{REQUEST_FILENAME}/index.php -f
RewriteRule ^(.+)/?$ $1/index.php [L]

RewriteCond %{REQUEST_FILENAME} -d
RewriteCond %{REQUEST_FILENAME}/index.html -f
RewriteRule ^(.+)/?$ $1/index.html [L]

# Trailing slash route -> /route.php if it exists
RewriteCond %{REQUEST_URI} ^/${baseTrimmed ? `${baseTrimmed}/` : ''}(.+)/$
RewriteCond %{DOCUMENT_ROOT}/${baseTrimmed ? `${baseTrimmed}/` : ''}%1.php -f
RewriteRule ^(.+)/$ $1.php [L]

# Handle client-side routing
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [QSA,L]

# Security headers
Header always set X-Content-Type-Options nosniff
Header always set X-Frame-Options DENY
Header always set X-XSS-Protection "1; mode=block"

# Compression
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/json
</IfModule>

# Cache control for static assets
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/gif "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType text/css "access plus 1 month"
    ExpiresByType application/javascript "access plus 1 month"
    ExpiresByType application/json "access plus 1 hour"
</IfModule>

${strict ? '# Strict mode - no directory listing\nOptions -Indexes' : '# Directory listing allowed in non-strict mode'}

# PHP settings
php_flag display_errors Off
php_flag log_errors On
php_value error_log error.log
`;
}

function generateApacheBootstrap(base: string): string {
	return `<?php
/**
 * Apache-optimized SvelteKit PHP bootstrap
 * Handles routing and SSR for Apache deployment
 */

// Error handling
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

// Get request URI
$uri = $_SERVER['REQUEST_URI'] ?? '/';
$path = parse_url($uri, PHP_URL_PATH);
$base = ${JSON.stringify(base.replace(/^\/+|\/+$/g, ''))};
if ($base !== '') {
    $prefix = '/' . $base;
    if (strpos($path, $prefix) === 0) {
        $path = substr($path, strlen($prefix));
        if ($path === '') $path = '/';
    }
}

// Remove trailing slash for consistency
$path = rtrim($path, '/') ?: '/';

// Handle static files directly
if (file_exists(__DIR__ . $path) && is_file(__DIR__ . $path)) {
    return false; // Let Apache serve the file
}

// Handle PHP files
if (file_exists(__DIR__ . $path . '.php')) {
    include __DIR__ . $path . '.php';
    return;
}

// Handle directories with index.php
if (file_exists(__DIR__ . $path . '/index.php')) {
    include __DIR__ . $path . '/index.php';
    return;
}

// Main application routing
$indexFile = __DIR__ . '/index.html';
if (file_exists($indexFile)) {
    // Serve the main application
    include $indexFile;
    return;
}

// 404 fallback
http_response_code(404);
echo '<h1>404 Not Found</h1>';
echo '<p>The requested page could not be found.</p>';
echo '<hr><small>SvelteKit Apache Adapter</small>';
?>`;
}

function generateDeploymentGuide(outDir: string): string {
	return `# Apache Deployment Guide

## Prerequisites
- Apache 2.4+ with mod_rewrite enabled
- PHP 8.1+ with required extensions
- Required modules: mod_rewrite, mod_headers
- Optional but recommended: mod_deflate, mod_expires
- Precompression support requires: mod_mime + mod_headers

## Installation Steps

1. **Upload Files**
   Upload all files from the \`${outDir}\` directory to your Apache document root (e.g., \`/var/www/html\`)

2. **Enable Required Apache Modules**
   \`\`\`bash
   sudo a2enmod rewrite
   sudo a2enmod deflate
   sudo a2enmod expires
   sudo a2enmod headers
   sudo systemctl restart apache2
   \`\`\`

3. **Set Permissions**
   \`\`\`bash
   sudo chown -R www-data:www-data /var/www/html
   sudo chmod -R 755 /var/www/html
   \`\`\`

4. **Configure Virtual Host (Optional)**
   Create/edit your Apache virtual host configuration:
   \`\`\`apache
   <VirtualHost *:80>
       ServerName your-domain.com
       DocumentRoot /var/www/html

       <Directory /var/www/html>
           AllowOverride All
           Require all granted
       </Directory>
   </VirtualHost>
   \`\`\`

## Required Rewrites

- Ensure requests for \`__data.json\` are routed to the PHP bridge (the adapter-generated \`.htaccess\` handles this).
- If you deploy to a subdirectory, set \`BASE_PATH\` during build so paths are correct.
- Keep \`AllowOverride All\` so the generated \`.htaccess\` is honored.

## Protecting \`_protected/\`

The \`_protected/\` directory contains server-side modules and must not be web-accessible.

- Confirm \`build/_protected/.htaccess\` includes \`Require all denied\`.
- If your host ignores per-directory \`.htaccess\`, block access in your vhost config.

## Testing

1. **Check .htaccess**: Visit \`http://your-domain.com/test\` - should redirect to index.php
2. **Check PHP**: Create a \`phpinfo.php\` file to verify PHP is working
3. **Check SSR**: Navigate to different routes to ensure server-side rendering works

## Troubleshooting

### Common Issues

1. **404 errors on routes**: Ensure mod_rewrite is enabled and .htaccess is readable
2. **PHP files not executing**: Check PHP installation and file permissions
3. **Static assets not loading**: Verify Apache can read the asset files
4. **Slow performance**: Enable mod_deflate and mod_expires

### Debug Mode

Add \`?debug=1\` to any URL to enable debug output.

## Security Considerations

- Keep your PHP version updated
- Use HTTPS in production
- Configure proper file permissions
- Consider implementing rate limiting
- Enable security headers in .htaccess

## Performance Optimization

- Enable OPcache for PHP
- Use a CDN for static assets
- Configure proper caching headers
- Consider using Apache's mod_cache
`;
}
