#!/usr/bin/env node

import { spawn } from 'child_process';
import { resolve } from 'path';
import { writeFile, mkdir } from 'fs/promises';
import { existsSync } from 'fs';

/**
 * Build script for Apache deployment
 * Creates production-ready files with Apache-specific optimizations
 */

const BUILD_DIR = resolve('build');

console.log('🚀 Building Apache deployment...');

// First run the standard build
console.log('📋 Running standard build...');
const buildProcess = spawn('vite', ['build'], {
	stdio: 'inherit',
	env: { ...process.env, NODE_ENV: 'production' }
});

buildProcess.on('close', async (code) => {
	if (code === 0) {
		console.log('✅ Standard build completed');

		// Now enhance with Apache-specific files
		console.log('🔧 Adding Apache-specific files...');

		try {
			// Create .htaccess file
			const htaccess = `# Apache configuration for SvelteKit PHP adapter
# Generated by @ryanspice/sveltekit-adapter-php-apache

# Enable rewrite engine
RewriteEngine On

# Handle client-side routing
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [QSA,L]

# Security headers
Header always set X-Content-Type-Options nosniff
Header always set X-Frame-Options DENY
Header always set X-XSS-Protection "1; mode=block"

# Compression
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/json
</IfModule>

# Cache control for static assets
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/gif "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType text/css "access plus 1 month"
    ExpiresByType application/javascript "access plus 1 month"
    ExpiresByType application/json "access plus 1 hour"
</IfModule>

# Strict mode - no directory listing
Options -Indexes

# PHP settings
php_flag display_errors Off
php_flag log_errors On
php_value error_log error.log
`;

			await writeFile(resolve(BUILD_DIR, '.htaccess'), htaccess, 'utf8');
			console.log('✅ Created .htaccess file');

			// Create Apache deployment guide
			const deploymentGuide = `# Apache Deployment Guide

## Prerequisites
- Apache 2.4+ with mod_rewrite enabled
- PHP 8.0+ with required extensions
- mod_deflate and mod_expires (optional but recommended)

## Quick Deployment

1. **Upload Files**
   Upload all files from the build/ directory to your Apache document root

2. **Enable Apache Modules**
   \`\`\`bash
   sudo a2enmod rewrite
   sudo a2enmod deflate
   sudo a2enmod expires
   sudo a2enmod headers
   sudo systemctl restart apache2
   \`\`\`

3. **Set Permissions**
   \`\`\`bash
   sudo chown -R www-data:www-data /var/www/html
   sudo chmod -R 755 /var/www/html
   \`\`\`

## Testing
- Visit your domain to test the application
- Check that routes work correctly
- Verify PHP files are executing

## Security
- Keep PHP updated
- Use HTTPS in production
- Configure proper file permissions
`;

			await writeFile(resolve(BUILD_DIR, 'APACHE_DEPLOYMENT.md'), deploymentGuide, 'utf8');
			console.log('✅ Created deployment guide');

			console.log('');
			console.log('🚀 Apache deployment ready!');
			console.log('📖 Check build/APACHE_DEPLOYMENT.md for detailed instructions');
			console.log('📁 Upload all files from build/ to your Apache server');

		} catch (error) {
			console.error('❌ Failed to create Apache files:', error);
			process.exit(1);
		}

	} else {
		console.error('❌ Build failed with code:', code);
		process.exit(1);
	}
});

buildProcess.on('error', (err) => {
	console.error('❌ Failed to build:', err);
	process.exit(1);
});
