#!/usr/bin/env node

import { spawn } from 'child_process';
import { resolve } from 'path';
import { access, writeFile } from 'fs/promises';
import { assertOptionalEnvIsConcrete } from './utils/config.mjs';

/**
 * Build script for Apache deployment
 * Creates production-ready files with Apache-specific optimizations
 */

const BUILD_DIR = resolve('build');
assertOptionalEnvIsConcrete(
	['SK_BASE_PATH', 'DEPLOY_BASE', 'ADAPTER_MODE', 'ADAPTER_OUT', 'ADAPTER_ASSETS'],
	'Apache build environment'
);

console.log('Building Apache deployment...');

// First run the standard build
console.log('Running standard build...');
const buildProcess = spawn('vite', ['build'], {
	stdio: 'inherit',
	env: { ...process.env, NODE_ENV: 'production' }
});

buildProcess.on('close', async (code) => {
	if (code === 0) {
		console.log('Standard build completed');

		// Now enhance with Apache-specific files
		console.log('Adding Apache-specific files...');

		try {
			// Preserve the adapter-generated .htaccess when present. The adapter output
			// contains base-path-aware routing rules for __data.json, actions, assets,
			// and router.php. Replacing it here breaks subdirectory deploys such as
			// /dev/sveltekitphp on shared Apache/PHP hosts.
			const htaccessPath = resolve(BUILD_DIR, '.htaccess');
			let hasAdapterHtaccess = false;
			try {
				await access(htaccessPath);
				hasAdapterHtaccess = true;
			} catch {
				hasAdapterHtaccess = false;
			}

			const htaccess = `# Apache configuration for SvelteKit PHP adapter
# Generated by @ryanspice/sveltekit-adapter-php-apache

# Enable rewrite engine
RewriteEngine On
DirectoryIndex index.php index.html

# Block access to protected runtime files
RewriteRule ^_protected/ - [F,L]
RewriteRule ^_runtime/ - [F,L]

# Route SvelteKit data/action requests before the generic fallback
RewriteRule ^(.*/)?__data\\.json$ $1__data.php [QSA,L]
RewriteRule ^(.*/)?__action$ $1__action.php [QSA,L]

# Let existing files and directories through
RewriteCond %{REQUEST_FILENAME} -f
RewriteRule ^ - [L]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]

# Serve directory PHP indexes when present
RewriteCond %{REQUEST_FILENAME}/index.php -f
RewriteRule ^(.+?)/?$ $1/index.php [QSA,L]

# Serve extensionless PHP route files when present
RewriteCond %{REQUEST_FILENAME}.php -f
RewriteRule ^(.+?)/?$ $1.php [QSA,L]

# Handle client-side routing
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ router.php [QSA,L]

# Security headers
Header always set X-Content-Type-Options nosniff
Header always set X-Frame-Options DENY
Header always set X-XSS-Protection "1; mode=block"

# Compression
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/json
</IfModule>

# Cache control for static assets
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/gif "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType text/css "access plus 1 month"
    ExpiresByType application/javascript "access plus 1 month"
    ExpiresByType application/json "access plus 1 hour"
</IfModule>

# Static artifact content types
<IfModule mod_mime.c>
    AddType text/markdown .md
    AddType text/csv .csv
    AddType image/svg+xml .svg
    AddType application/json .json
</IfModule>

# Strict mode - no directory listing
Options -Indexes

# PHP settings belong in the host control panel/php.ini. Shared PHP-FPM hosts
# commonly reject php_flag/php_value in .htaccess, which turns every request
# into HTTP 500.
`;

			if (hasAdapterHtaccess) {
				console.log('Preserved adapter-generated .htaccess file');
			} else {
				await writeFile(htaccessPath, htaccess, 'utf8');
				console.log('Created fallback .htaccess file');
			}

			// Create Apache deployment guide
			const deploymentGuide = `# Apache Deployment Guide

## Prerequisites
- Apache 2.4+ with mod_rewrite enabled
- PHP 7.4+ with required extensions
- Required modules: mod_rewrite, mod_headers
- Optional but recommended: mod_deflate, mod_expires
- Precompression support requires: mod_mime + mod_headers

## Quick Deployment

1. **Upload Files**
   Upload all files from the build/ directory to your Apache document root

2. **Enable Apache Modules**
   \`\`\`bash
   sudo a2enmod rewrite
   sudo a2enmod deflate
   sudo a2enmod expires
   sudo a2enmod headers
   sudo systemctl restart apache2
   \`\`\`

3. **Set Permissions**
   \`\`\`bash
   sudo chown -R www-data:www-data /var/www/html
   sudo chmod -R 755 /var/www/html
   \`\`\`

## Testing
- Visit your domain to test the application
- Check that routes work correctly
- Verify PHP files are executing

## Required Rewrites
- Ensure requests for \`__data.json\` are routed to the PHP bridge (the generated \`.htaccess\` handles this).
- If you deploy to a subdirectory, set \`SK_BASE_PATH\` or \`DEPLOY_BASE\` during build so paths are correct.

## Environment
- Keep real deployment values in process environment variables or CI secrets.
- Use \`.env.example\` as the public template.
- Run \`bun run precheck:deploy\` before deploy automation.

## Protecting \`_protected/\`
- Confirm \`build/_protected/.htaccess\` includes \`Require all denied\`.
- If your host ignores per-directory \`.htaccess\`, block access in your vhost config.

## Security
- Keep PHP updated
- Use HTTPS in production
- Configure proper file permissions
`;

			await writeFile(resolve(BUILD_DIR, 'APACHE_DEPLOYMENT.md'), deploymentGuide, 'utf8');
			console.log('Created deployment guide');

			console.log('');
			console.log('Apache deployment ready.');
			console.log('Check build/APACHE_DEPLOYMENT.md for detailed instructions.');
			console.log('Upload all files from build/ to your Apache server.');
		} catch (error) {
			console.error('Failed to create Apache files:', error);
			process.exit(1);
		}
	} else {
		console.error('Build failed with code:', code);
		process.exit(1);
	}
});

buildProcess.on('error', (err) => {
	console.error('Failed to build:', err);
	process.exit(1);
});
