import { getRouterJsSsrPhp } from './router/js-ssr';
import { getRouterPhpStaticPhp } from './router/php-static';
import { getRouterSharedPhp } from './router/shared';

export function getDataPhp(
	includes: string[],
	base: string = '',
	compatRel: string = './_runtime/compat.php',
	relToRoot: string = './'
) {
	return `<?php
/**
 * Generated by sveltekit-php
 * - Serves /__data.php requests (client navigation + invalidations)
 * - Provides sk_build_embed_data() for index.php hydration
 *
 * Template shape comes from prerendered __data.json (so it matches your Kit version).
 */

declare(strict_types=1);

// Runtime Hardening
if (!defined('SK_HARDENED')) {
	define('SK_HARDENED', 1);
	// 1. Output Buffering
	if (ob_get_level() === 0) ob_start();

	// 2. Error Output Policy
	ini_set('display_errors', '0');
	ini_set('log_errors', '1');
	ini_set('error_log', 'php://stderr');

	// 3. Capture warnings/notices
	set_error_handler(function($severity, $message, $file, $line) {
		if (!(error_reporting() & $severity)) {
			return false;
		}
		error_log("[php-warning] $message in $file:$line");
		return true;
	});
}

require_once __DIR__ . '/${compatRel}';

// Define relative path to root for runtime base detection
if (!defined('SK_REL_TO_ROOT')) {
	define('SK_REL_TO_ROOT', '${relToRoot}');
}

// Allow env override for base path (e.g. for different dev/prod paths)
// Fallback to build-time base
if (!defined('SK_BASE_PATH')) {
	define('SK_BASE_PATH', getenv('SK_BASE_PATH') ?: '${base}');
}
if (!defined('SK_ROUTE_REGEX')) {
	define('SK_ROUTE_REGEX', 'PLACEHOLDER_ROUTE_REGEX');
}
if (!defined('SK_ROUTE_PARAM_MAP')) {
	define('SK_ROUTE_PARAM_MAP', PLACEHOLDER_ROUTE_PARAM_MAP);
}

${includes.join('\n')}

if (!function_exists('sk_json_encode')) {
function sk_json_encode($value): string {
	$json = json_encode(
		$value,
		JSON_UNESCAPED_SLASHES
			| JSON_UNESCAPED_UNICODE
			| JSON_HEX_TAG
			| JSON_HEX_AMP
			| JSON_HEX_APOS
			| JSON_HEX_QUOT
	);
	return $json === false ? 'null' : $json;
}
}

if (!class_exists('SK_URLSearchParams')) {
final class SK_URLSearchParams {
	private array $pairs = [];

	public function __construct(string $queryString) {
		$qs = ltrim($queryString, '?');
		if ($qs === '') return;
		foreach (explode('&', $qs) as $part) {
			if ($part === '') continue;
			$kv = explode('=', $part, 2);
			$key = urldecode($kv[0]);
			$val = urldecode($kv[1] ?? '');
			if (!array_key_exists($key, $this->pairs)) $this->pairs[$key] = [];
			$this->pairs[$key][] = $val;
		}
	}

	public function get(string $key): ?string {
		$vals = $this->pairs[$key] ?? null;
		if (!$vals) return null;
		return $vals[0] ?? null;
	}

	public function has(string $key): bool {
		return array_key_exists($key, $this->pairs);
	}

	public function __get(string $key): ?string {
		return $this->get($key);
	}

	public function __isset(string $key): bool {
		return $this->has($key);
	}

	public function all(string $key): array {
		return $this->pairs[$key] ?? [];
	}

	public function toString(): string {
		$out = [];
		foreach ($this->pairs as $k => $vals) {
			foreach ($vals as $v) {
				$out[] = rawurlencode($k) . '=' . rawurlencode($v);
			}
		}
		return implode('&', $out);
	}
}
}

if (!class_exists('__SK_Deferred')) {
final class __SK_Deferred {
	public $fn;
	public function __construct($fn) {
		$this->fn = $fn;
	}
}
}
if (!class_exists('__SK_Deferred_Placeholder')) {
final class __SK_Deferred_Placeholder {
	public int $id;
	public function __construct(int $id) {
		$this->id = $id;
	}
}
}

if (!function_exists('sk_defer')) {
function sk_defer(callable $fn): __SK_Deferred { return new __SK_Deferred($fn); }
}


if (!function_exists('sk_assert_jsonable')) {
function sk_assert_jsonable($value, string $path = '', int $depth = 0): void {
	if ($depth > 256) {
		throw new RuntimeException("Possible cyclic or too-deep JSON value at $path");
	}
	if ($value instanceof __SK_Deferred || $value instanceof __SK_Deferred_Placeholder) return;
	if (is_null($value) || is_bool($value) || is_int($value) || is_string($value)) return;
	if (is_float($value)) {
		if (is_nan($value) || is_infinite($value)) {
			throw new RuntimeException("Non-JSON float at $path");
		}
		return;
	}
	if (is_array($value)) {
		foreach ($value as $k => $v) {
			$next = $path === '' ? (string)$k : ($path . '.' . (string)$k);
			sk_assert_jsonable($v, $next, $depth + 1);
		}
		return;
	}
	if (is_object($value)) {
		if ($value instanceof JsonSerializable) {
			sk_assert_jsonable($value->jsonSerialize(), $path, $depth + 1);
			return;
		}
		throw new RuntimeException("Non-JSON object at $path");
	}
	if (is_resource($value)) throw new RuntimeException("Non-JSON resource at $path");
	throw new RuntimeException("Non-JSON value at $path");
}
}

if (!function_exists('sk_recursive_resolve')) {
function sk_recursive_resolve($data, ?array &$deferreds = null) {
	if ($data instanceof __SK_Deferred) {
		if ($deferreds !== null) {
			$id = count($deferreds) + 1;
			$deferreds[$id] = $data;
			return new __SK_Deferred_Placeholder($id);
		}
		$fn = $data->fn;
		return sk_recursive_resolve($fn(), $deferreds);
	}
	if (is_array($data)) {
		foreach ($data as $k => $v) {
			$data[$k] = sk_recursive_resolve($v, $deferreds);
		}
	}
	return $data;
}
}

/**
 * Locates the "nodes" array within the template payload.
 * Supports:
 *   A) { "type":"data", "nodes":[ ... ] }
 *   B) devalue-like: [ { "type":1, "nodes":2 }, ..., <nodes at index 2>, ... ]
 */
if (!function_exists('sk_get_nodes_ref')) {
function sk_get_nodes_ref(array &$payload): array {
	// A) associative with nodes
	if (array_key_exists('nodes', $payload) && is_array($payload['nodes'])) {
		return ['kind' => 'assoc', 'key' => 'nodes'];
	}

	// B) packed array with header object at 0
	if (isset($payload[0]) && is_array($payload[0]) && array_key_exists('nodes', $payload[0]) && is_int($payload[0]['nodes'])) {
		$idx = $payload[0]['nodes'];
		if (isset($payload[$idx]) && is_array($payload[$idx])) {
			return ['kind' => 'index', 'idx' => $idx];
		}
	}

	// fallback: treat as already nodes
	return ['kind' => 'self'];
}
}

if (!function_exists('sk_serialize')) {
function sk_serialize($value): array {
	$flattened = [];
	$map = [];
	$object_stack = [];

	$add_primitive = function($val) use (&$flattened, &$map) {
		$key = is_string($val)
			? 's_'.$val
			: (is_int($val)
				? 'i_'.$val
				: (is_float($val) ? 'f_'.$val : json_encode($val)));
		if (array_key_exists($key, $map)) {
			return $map[$key];
		}

		$flattened[] = $val;
		$idx = count($flattened) - 1;
		$map[$key] = $idx;
		return $idx;
	};

	// Recursive closure to flatten the structure.
	// Composite identity is intentionally not deduped into shared references; this keeps output
	// devalue-compatible enough for SvelteKit hydration while avoiding incorrect identity claims.
	$fn = function($val, int $depth = 0) use (&$flattened, &$map, &$object_stack, &$fn, $add_primitive) {
		if ($depth > 256) {
			throw new RuntimeException('Cannot serialize cyclic or too-deep data structure');
		}

		// Primitives
		if (is_string($val) || is_int($val) || is_float($val) || is_bool($val) || is_null($val)) {
			return $add_primitive($val);
		}

		if ($val instanceof __SK_Deferred_Placeholder) {
			$id_idx = $add_primitive($val->id);
			$flattened[] = ["Promise", $id_idx];
			return count($flattened) - 1;
		}

		if (!is_array($val) && !is_object($val)) {
			throw new RuntimeException('Cannot serialize unsupported value type');
		}

		if (is_object($val)) {
			$oid = spl_object_id($val);
			if (isset($object_stack[$oid])) {
				throw new RuntimeException('Cannot serialize cyclic object graph');
			}
			$object_stack[$oid] = true;
		}

		// Arrays / Objects
		// Detect if it's a list (array) or object (associative)
		$is_list = is_array($val) && array_is_list($val);
		$flattened[] = $is_list ? [] : (object)[];
		$idx = count($flattened) - 1;
		$map['o_'.$idx] = $idx;

		foreach ($val as $k => $v) {
			$vIdx = $fn($v, $depth + 1);
			if (is_array($flattened[$idx])) {
				$flattened[$idx][] = $vIdx;
			} else {
				$flattened[$idx]->{$k} = $vIdx;
			}
		}
		if (is_object($val)) {
			unset($object_stack[spl_object_id($val)]);
		}
		return $idx;
	};

	$fn($value);
	return $flattened;
}
}

/**
 * Unflattens a Devalue-serialized array back into a PHP structure (array/object).
 * This is used to provide hydrated data to the client in a format SvelteKit's start() accepts (objects).
 */
if (!function_exists('sk_unflatten')) {
function sk_unflatten(array $data) {
	if (empty($data)) return null;

	$resolve = function($idx) use ($data, &$resolve) {
		$val = $data[$idx] ?? null;

		// Primitives are returned as-is
		if (!is_array($val) && !is_object($val)) {
			return $val;
		}

		// Handle stdClass (from sk_serialize)
		if (is_object($val)) {
			$val = (array)$val;
			$res = (object)[];
			foreach ($val as $k => $i) {
				$res->{$k} = $resolve($i);
			}
			return $res;
		}

		// Handle arrays (from json_decode or sk_serialize)
		// Check for array vs object (associative)
		// Polyfill for array_is_list: keys are 0..count-1
		$is_list = $val === [] || (array_keys($val) === range(0, count($val) - 1));

		if ($is_list) {
			$res = [];
			foreach ($val as $i) {
				$res[] = $resolve($i);
			}
			return $res;
		} else {
			$res = (object)[];
			foreach ($val as $k => $i) {
				$res->{$k} = $resolve($i);
			}
			return $res;
		}
	};

	// Devalue root is always at index 0
	return $resolve(0);
}
}

if (!function_exists('sk_set_node_data')) {
function sk_set_node_data(&$node, $server_data): void {
	if (!is_array($node)) {
		$node = [];
	}

	$node['type'] = 'data';

	sk_assert_jsonable($server_data);

	// SvelteKit expects data to be the serialized array (devalue format).
	// We use sk_serialize to produce a devalue-compatible flattened array.
	// We force array_values to ensure it's encoded as a JSON list, not an object.
	$encoded = sk_serialize($server_data);
	$node['data'] = array_values($encoded);

	$node['uses'] = $node['uses'] ?? (object)[];
	// Force uses to be an object if it's an empty array
	if (is_array($node['uses']) && count($node['uses']) === 0) {
		$node['uses'] = (object)[];
	}
}
}

if (!function_exists('sk_set_payload_form')) {
function sk_set_payload_form(&$payload, $form): void {
	if (is_array($payload) && isset($payload[0]) && is_array($payload[0])) {
		$payload[0]['form'] = $form;
		return;
	}

	if (is_array($payload)) {
		$payload['form'] = $form;
	}
}
}

if (!function_exists('sk_apply_loads')) {
function sk_apply_loads(string $routeid, array $loadFns, array &$payload, string $inline_mode, ?array &$deferreds = null): array {
	$base = [];
	$server_results = [];
	$next_chunk_id = 1;
	$params = sk_extract_params($_SERVER['REQUEST_URI'] ?? '', SK_BASE_PATH, SK_ROUTE_REGEX, SK_ROUTE_PARAM_MAP);

	// Loop through load functions (from root layout to leaf page)
	foreach ($loadFns as $i => $fn) {
		if (!function_exists($fn)) {
			continue;
		}

		// Prepare URL object to match dev environment
		$qs = $_SERVER['QUERY_STRING'] ?? '';
		$searchParams = new SK_URLSearchParams($qs);
		sk_debug_log("DEBUG: sk_apply_loads - route: $routeid, fn: $fn, qs: $qs");

		// Execute the load function
		// Pass $base (merged parent data) as 'parentdata' if needed, though SvelteKit usually
		// passes a parent() function. For this simple adapter, we simulate parent merging
		// by accumulating data in $base.
		$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
		$locals = &sk_locals();

		try {
			$res = $fn([
				'params' => $params,
				'url' => (object)[
					'searchParams' => $searchParams,
					'pathname' => $_SERVER['REQUEST_URI'] ?? ''
				],
				'request' => (object)[
					'method' => $method,
					'headers' => (object)[
						'cookie' => $_SERVER['HTTP_COOKIE'] ?? ''
					]
				],
				'cookies' => new SK_Cookies($_COOKIE),
				'route' => (object)[
					'id' => $routeid
				],
				'parent' => function() use (&$base) {
					return $base;
				},
				'locals' => &$locals,
				'depends' => function(...$deps) {
					return null;
				},
				'fetch' => function($input, $init = []) {
					return sk_fetch($input, $init ?? []);
				},
				'routeid' => $routeid,
				'parentdata' => $base,
				'method' => $method,
				'query' => $_GET,
				'server' => $_SERVER
			]);
		} catch (SK_Redirect $e) {
			header('Location: ' . $e->location, true, $e->status);
			exit;
		} catch (SK_Error $e) {
			http_response_code($e->status);
			echo sk_json_encode(['error' => $e->body]);
			exit;
		}

		// Merge result into base for next level
		if (is_array($res)) {
			$res = sk_recursive_resolve($res, $deferreds);
			$base = array_merge($base, $res);
			$server_results[$i] = $res;
		} else {
			// Handle non-array results? (e.g. redirect/error usually throw)
			$res = sk_recursive_resolve($res, $deferreds);
			$server_results[$i] = $res;
		}
	}

    sk_debug_log("DEBUG: server_results=" . json_encode($server_results));

	// Update the payload with server results
	$ref = sk_get_nodes_ref($payload);

	// Helper to access nodes array by reference
	$nodes = [];
	if ($ref['kind'] === 'assoc') {
		$nodes = &$payload[$ref['key']];
	} else if ($ref['kind'] === 'index') {
		$nodes = &$payload[$ref['idx']];
	} else {
		$nodes = &$payload;
	}

	foreach ($server_results as $i => $data) {
		// Map load index to node index
		// $i is string (key from loadFns)
		$nodeIdx = $i;

		if (array_key_exists($nodeIdx, $nodes)) {
			sk_set_node_data($nodes[$nodeIdx], $data);
		}
	}

	// Inline Mode: return full payload (no streaming needed for now)
	return $payload;
}
}

if (!function_exists('sk_build_embed_data')) {
function sk_build_embed_data(string $routeid, array $loadFns, string $templateJson, string $inline_mode, bool $streaming = false): array {
	$payload = json_decode($templateJson, true);
	if (!$payload) return ['[]', []];

	$deferreds = $streaming ? [] : null;
	$finalPayload = sk_apply_loads($routeid, $loadFns, $payload, $inline_mode, $deferreds);
	if (array_key_exists('__SK_ACTION_RESULT', $GLOBALS)) {
		sk_set_payload_form($finalPayload, $GLOBALS['__SK_ACTION_RESULT']);
	}

	// Extract nodes to generate the hydration array
	$ref = sk_get_nodes_ref($finalPayload);
	$nodes = [];
	if ($ref['kind'] === 'assoc') {
		$nodes = $finalPayload[$ref['key']];
	} elseif ($ref['kind'] === 'index') {
		$nodes = $finalPayload[$ref['idx']];
	} else {
		$nodes = $finalPayload;
	}

	$outputPayload = $finalPayload;

	// If inline_mode is 'nodes', we want the parallel array of data objects
	// SvelteKit hydration expects [ data_0, data_1, ... ] matching node_ids
	// The nodes are usually objects like { type: 'data', data: [...], uses: ... }
	// We should return them AS IS (preserving Devalue structure) because SvelteKit client will deserialize them.
	if ($inline_mode === 'nodes' || $inline_mode === 'unknown') {
		$outputPayload = $nodes;
	}

	$json = sk_json_encode($outputPayload);
	if (sk_debug_enabled()) {
		file_put_contents('debug_payload.json', $json . "\n", FILE_APPEND);
	}

	// Replace deferred placeholders with JS calls
	if ($streaming && $deferreds) {
		// We need to be careful not to replace things inside strings that look like our marker,
		// but our marker is very specific.
		// The marker is "%%%SK_DEFER_ID%%%" (quoted in JSON).
		// We want to replace "%%%SK_DEFER_ID%%%" with PLACEHOLDER_APP_ID.defer(ID).
		// Note the lack of quotes in the replacement.

		$json = preg_replace_callback('/"%%%SK_DEFER_(\\d+)%%%"/', function($matches) {
			$id = (int)$matches[1];
			// sk_recursive_resolve uses 1-based IDs to match SvelteKit chunk ids.
			return "PLACEHOLDER_APP_ID.defer($id)";
		}, $json);
	}

	return [$json, $deferreds];
}
}

// Main execution if called directly (client navigation)
if (basename($_SERVER['SCRIPT_FILENAME']) === '__data.php') {
	header('Content-Type: application/json; charset=utf-8');

    // Intercept redirects to ensure they point to __data.json
    // This fixes the issue where SvelteKit client navigation receives HTML instead of JSON
    // when a load function redirects to a page URL.
    register_shutdown_function(function() {
        if (headers_sent()) return;

        $headers = headers_list();
        foreach ($headers as $h) {
            // Case-insensitive check for Location header
            if (stripos($h, 'Location:') === 0) {
                $location = trim(substr($h, 9));

                // If redirecting to a page (not already __data.json)
                if (strpos($location, '__data.json') === false) {
                    // Only rewrite local paths (starting with /)
                    // This covers most SvelteKit redirects.
                    if (strpos($location, '/') === 0) {
                         $parts = parse_url($location);
                         $path = $parts['path'] ?? '';

                         // Append /__data.json
                         // SvelteKit normalization usually strips trailing slash, but we are appending a file.
                         // /foo -> /foo/__data.json
                         // /foo/ -> /foo/__data.json
                         $newPath = rtrim($path, '/') . '/__data.json';
						 if (SK_BASE_PATH !== '' && strpos($newPath, SK_BASE_PATH . '/') !== 0 && $newPath !== SK_BASE_PATH) {
							 $newPath = SK_BASE_PATH . $newPath;
						 }

                         $newLocation = $newPath;
                         if (isset($parts['query'])) $newLocation .= '?' . $parts['query'];
                         if (isset($parts['fragment'])) $newLocation .= '#' . $parts['fragment'];

                         // Replace the Location header
                         header("Location: $newLocation", true);
                    }
                }
            }
        }
	});

	// Execute loads
	$templateJson = base64_decode('PLACEHOLDER_TEMPLATE_B64');
	$payload = json_decode(is_string($templateJson) ? $templateJson : '', true);
	$loadFns = PLACEHOLDER_LOAD_FNS;
	$routeId = PLACEHOLDER_ROUTE_ID;
	$inlineMode = PLACEHOLDER_INLINE_MODE;

	// Blocking mode for client navigation
	sk_debug_log("DEBUG: __data.php processing request for $routeId");
	$finalPayload = sk_apply_loads($routeId, $loadFns, $payload, $inlineMode);
	$json = sk_json_encode($finalPayload);

	header('Content-Length: ' . strlen($json));

	if ($_SERVER['REQUEST_METHOD'] !== 'HEAD') {
		echo $json;
	}
	sk_debug_log("DEBUG: __data.php response sent");
}
`;
}

export function getActionPhp(
	includes: string[],
	routeId: string,
	pagePrefix: string | null,
	compatRel: string = './_runtime/compat.php'
) {
	return `<?php
/**
 * Generated by sveltekit-php
 * - Handles form actions (POST)
 */

declare(strict_types = 1);

require_once __DIR__ . '/${compatRel}';

${includes.join('\n')}

require_once __DIR__ . '/__data.php';

// Helper for SvelteKit fail()
if (!function_exists('sk_fail')) {
function sk_fail(int $status, $data): array {
	return ['type' => 'failure', 'status' => $status, 'data' => $data];
}
}

if (!function_exists('sk_action_serialize')) {
function sk_action_serialize($value): string {
	return sk_json_encode(array_values(sk_serialize($value)));
}
}

if (!function_exists('sk_action_content_type')) {
function sk_action_content_type(): string {
	$raw = $_SERVER['CONTENT_TYPE'] ?? $_SERVER['HTTP_CONTENT_TYPE'] ?? '';
	$parts = explode(';', (string)$raw, 2);
	return strtolower(trim($parts[0]));
}
}

if (!function_exists('sk_action_raw_body')) {
function sk_action_raw_body(): string {
	static $body = null;
	if ($body === null) $body = file_get_contents('php://input') ?: '';
	return $body;
}
}

if (!function_exists('sk_action_parse_body')) {
function sk_action_parse_body() {
	$contentType = sk_action_content_type();

	if ($contentType === 'application/json' || str_ends_with($contentType, '+json')) {
		$decoded = json_decode(sk_action_raw_body(), true);
		return json_last_error() === JSON_ERROR_NONE ? $decoded : null;
	}

	if ($contentType === 'application/x-www-form-urlencoded' && empty($_POST)) {
		$parsed = [];
		parse_str(sk_action_raw_body(), $parsed);
		return $parsed;
	}

	if (!empty($_POST)) return $_POST;

	$raw = sk_action_raw_body();
	return $raw === '' ? [] : ['_body' => $raw];
}
}

if (!function_exists('sk_action_form_data')) {
function sk_action_form_data(): array {
	$parsed = sk_action_parse_body();
	$form = is_array($parsed) ? $parsed : ['_body' => $parsed];
	return array_merge($form, $_FILES);
}
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
	http_response_code(405);
	exit('Method Not Allowed');
}

// 1. Determine Action Name
// SvelteKit passes action name in query string usually ?/actionName
// Or default action if ?/
$actionName = 'default';
foreach($_GET as $key => $val) {
	if (str_starts_with($key, '/')) {
		$name = substr($key, 1);
		$actionName = $name === '' ? 'default' : $name;
		break;
	}
}

// 2. Call the action
$isEnhanced = (($_SERVER['HTTP_X_SVELTEKIT_ACTION'] ?? '') === 'true');
$pagePrefix = ${pagePrefix ? `'${pagePrefix}'` : "''"};
$fnName = $pagePrefix . '_action_' . $actionName;

if (!function_exists($fnName)) {
	http_response_code(404);
	header('Content-Type: application/json; charset=utf-8');
	echo sk_json_encode(['type' => 'error', 'error' => ['message' => 'Action not found']]);
	exit;
}

// 3. Execute
// PHP populates $_POST only for form-urlencoded and multipart bodies.
// Fall back to php://input so JSON/raw action posts do not silently become empty input.

try {
	$params = sk_extract_params($_SERVER['REQUEST_URI'] ?? '', SK_BASE_PATH, SK_ROUTE_REGEX, SK_ROUTE_PARAM_MAP);
	$method = $_SERVER['REQUEST_METHOD'] ?? 'POST';
	$locals = &sk_locals();
	$actionBody = sk_action_parse_body();
	$actionFormData = sk_action_form_data();

	$result = $fnName([
		'request' => (object)[
			'method' => $method,
			'formData' => function () {
				return sk_action_form_data();
			},
			'body' => $actionBody,
			'rawBody' => sk_action_raw_body(),
			'json' => function () {
				return json_decode(sk_action_raw_body(), true);
			},
			'text' => function () {
				return sk_action_raw_body();
			}
		],
		'url' => (object)[
			'searchParams' => new SK_URLSearchParams($_SERVER['QUERY_STRING'] ?? ''),
			'pathname' => parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH)
		],
		'params' => $params,
		'route' => (object)[
			'id' => ${JSON.stringify(routeId)}
		],
		'locals' => &$locals,
		'depends' => function(...$deps) {
			return null;
		},
		'fetch' => function($input, $init = []) {
			return sk_fetch($input, $init ?? []);
		},
		'cookies' => new SK_Cookies($_COOKIE),
		'post' => is_array($actionBody) ? $actionBody : ['_body' => $actionBody],
		'body' => $actionBody,
		'rawBody' => sk_action_raw_body(),
		'formData' => $actionFormData,
		'files' => $_FILES
    ]);

	// 4. Return result
	// SvelteKit actions return { type: 'success'|'failure'|'redirect'|'error', data: ... }
	// We assume the PHP code returns an array/object matching this.

	if ($isEnhanced) {
		header('Content-Type: application/json; charset=utf-8');
		echo sk_action_serialize($result);
		exit;
	}

	$accept = $_SERVER['HTTP_ACCEPT'] ?? '';
	$expectsJson = strpos($accept, 'application/json') !== false;

	if (isset($result['type']) && $result['type'] === 'redirect') {
		if ($expectsJson) {
			header('Content-Type: application/json; charset=utf-8');
			echo sk_json_encode($result);
			exit;
		}

		header('Location: '.$result['location']);
		http_response_code($result['status'] ?? 303);
		exit;
	}

	if ($expectsJson) {
		header('Content-Type: application/json; charset=utf-8');
		echo sk_json_encode($result);
		exit;
	}

	if (isset($result['type']) && $result['type'] === 'failure') {
		http_response_code($result['status'] ?? 400);
		$GLOBALS['__SK_ACTION_RESULT'] = $result['data'] ?? null;
		return;
	}

	if (isset($result['type']) && $result['type'] === 'error') {
		http_response_code($result['status'] ?? 500);
		$GLOBALS['__SK_ACTION_RESULT'] = $result['error'] ?? null;
		return;
	}

	if (isset($result['type']) && $result['type'] === 'success') {
		$GLOBALS['__SK_ACTION_RESULT'] = $result['data'] ?? null;
		return;
	}

	if (is_array($result)) {
		$GLOBALS['__SK_ACTION_RESULT'] = $result;
		return;
	}

	http_response_code(500);

} catch (SK_Redirect $e) {
	if (!$isEnhanced) {
		header('Location: ' . $e->location, true, $e->status);
		exit;
	}
	header('Content-Type: application/json; charset=utf-8');
	echo sk_json_encode(['type' => 'redirect', 'location' => $e->location, 'status' => $e->status]);
	exit;
} catch (SK_Error $e) {
	http_response_code($e->status);
	if ($isEnhanced) {
		header('Content-Type: application/json; charset=utf-8');
		echo sk_json_encode(['type' => 'error', 'error' => $e->body, 'status' => $e->status]);
		exit;
	}
	$GLOBALS['__SK_ACTION_RESULT'] = $e->body;
	return;
} catch (Throwable $e) {
	http_response_code(500);
	error_log('[sveltekit-php] action error: ' . $e->getMessage());
	header('Content-Type: application/json; charset=utf-8');
	echo sk_json_encode(['type' => 'error', 'error' => ['message' => 'Internal Server Error'], 'status' => 500]);
	exit;
}
`;
}

export function getBootstrapPhp(
	routeId: string,
	loadFns: string,
	templateJson: string,
	inlineMode: string,
	requirePrefix: string = ''
) {
	const templateB64 = Buffer.from(templateJson, 'utf8').toString('base64');
	return `<?php
require_once __DIR__ . '${requirePrefix}/__data.php';

ini_set('output_buffering', '0');
ini_set('zlib.output_compression', '0');
ini_set('implicit_flush', '1');
while (ob_get_level()) ob_end_flush();

// Handle Actions (POST)
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    sk_debug_log("DEBUG: index.php handling POST for " . $_SERVER['REQUEST_URI']);
    if (file_exists(__DIR__ . '${requirePrefix}/__action.php')) {
        require __DIR__ . '${requirePrefix}/__action.php';
    } else {
        sk_debug_log("DEBUG: __action.php not found in " . __DIR__ . '${requirePrefix}');
    }
}

$routeId = ${JSON.stringify(routeId)};
$loadFns = ${loadFns};
$templateJson = base64_decode('${templateB64}');
$inlineMode = ${JSON.stringify(inlineMode)};

// Build data with streaming support
list($data, $sk_deferreds) = sk_build_embed_data($routeId, $loadFns, $templateJson, $inlineMode, true);

$dataPayload = $data;
sk_debug_log("DEBUG: dataPayload=" . substr($dataPayload, 0, 500));

// Fix PLACEHOLDER_APP_ID in streaming promises
// We can't do this in sk_build_embed_data because we don't know the appId yet
// But wait, sk_build_embed_data returns JSON string with placeholders if we used PLACEHOLDER_APP_ID.
// The regex in sk_build_embed_data replaced the deferred marker with a JS call.
// We need to replace PLACEHOLDER_APP_ID with the actual appId found in HTML.
// But we find appId AFTER generating this PHP block.
// Solution: We inject a PHP variable for appId, or we rely on the client-side variable being available.
// SvelteKit usually assigns the app to a variable like '__sveltekit_xyz'.
// We need to ensure our injected script uses the CORRECT variable.
// But we are prepending PHP.
// We can use a JS variable that we define? No, SvelteKit defines it.

// Let's assume we can replace it in the output HTML buffer or we inject a script that defines a bridge.
// OR we just use 'document.currentScript.parentElement' context? No, defer calls are global.

// Revert to using a known variable if possible, or parsing it.
// The adapter index.ts finds the appHash and passes it to getFooterPhp.
// Can we pass it to getBootstrapPhp?
// Yes, we call getBootstrapPhp in index.ts. We should pass appHash there.
?>`;
}

export function getFooterPhp(appId: string) {
	return `<?php
// Footer to handle streaming
// Flush HTML
while (ob_get_level()) ob_end_flush();
flush();

sk_debug_log("DEBUG: Footer running. deferreds count: " . (isset($sk_deferreds) ? count($sk_deferreds) : '0'));

if (!empty($sk_deferreds)) {
	foreach($sk_deferreds as $id => $deferred) {
		$fn = $deferred -> fn;
		// Resolve
		// We use sk_recursive_resolve to resolve the deferred value (blocking for this chunk)
		$data = sk_recursive_resolve($fn());

		// Serialize
		// TODO: Support full Devalue serialization for deferreds (requires client-side unflattening)
		// For now, we use simple JSON encoding to avoid the need for unflattening on the client.
		$serialized = sk_json_encode($data);

		echo '<script>if(typeof ${appId} !== "undefined") { ${appId}.resolve('.$id. ', () => ['.$serialized.', null]); } else { globalThis.console.error("App ID undefined: ${appId}"); }</script>';
		flush();
	}
}
?>`;
}

export function getMinimalBootstrapPhp(requirePrefix: string = '') {
	return `<?php
// Minimal bootstrap for actions only (SSR=false or no data)
// Keep GET/HEAD page requests on the generated HTML shell; delegate only action posts.
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST' && file_exists(__DIR__ . '${requirePrefix}/__action.php')) {
		require __DIR__ . '${requirePrefix}/__action.php';
	}
?>
`;
}

export function getApiPhp(
	includes: string[],
	prefix: string,
	base: string,
	routeRegex: string,
	routeParamMapPhp: string,
	compatRel: string = './_runtime/compat.php',
	relToRoot: string = './'
) {
	return `<?php
/**
 * Generated by sveltekit-php
 * - Handles API endpoints (+server.php)
 */
declare(strict_types=1);

require_once __DIR__ . '/${compatRel}';

// Define relative path to root for runtime base detection
if (!defined('SK_REL_TO_ROOT')) {
	define('SK_REL_TO_ROOT', '${relToRoot}');
}

// Allow env override for base path
define('SK_BASE_PATH', getenv('SK_BASE_PATH') ?: '${base}');
const SK_ROUTE_REGEX = '${routeRegex}';
const SK_ROUTE_PARAM_MAP = ${routeParamMapPhp};

${includes.join('\n')}

if (!function_exists('sk_json_encode')) {
function sk_json_encode($value): string {
	$json = json_encode(
		$value,
		JSON_UNESCAPED_SLASHES
			| JSON_UNESCAPED_UNICODE
			| JSON_HEX_TAG
			| JSON_HEX_AMP
			| JSON_HEX_APOS
			| JSON_HEX_QUOT
	);
	return $json === false ? 'null' : $json;
}
}

if (!class_exists('SK_URLSearchParams')) {
final class SK_URLSearchParams {
	private array $pairs = [];

	public function __construct(string $queryString) {
		$qs = ltrim($queryString, '?');
		if ($qs === '') return;
		foreach (explode('&', $qs) as $part) {
			if ($part === '') continue;
			$kv = explode('=', $part, 2);
			$key = urldecode($kv[0]);
			$val = urldecode($kv[1] ?? '');
			if (!array_key_exists($key, $this->pairs)) $this->pairs[$key] = [];
			$this->pairs[$key][] = $val;
		}
	}

	public function get(string $key): ?string {
		$vals = $this->pairs[$key] ?? null;
		if (!$vals) return null;
		return $vals[0] ?? null;
	}

	public function has(string $key): bool {
		return array_key_exists($key, $this->pairs);
	}

	public function __get(string $key): ?string {
		return $this->get($key);
	}

	public function __isset(string $key): bool {
		return $this->has($key);
	}

	public function all(string $key): array {
		return $this->pairs[$key] ?? [];
	}

	public function toString(): string {
		$out = [];
		foreach ($this->pairs as $k => $vals) {
			foreach ($vals as $v) {
				$out[] = rawurlencode($k) . '=' . rawurlencode($v);
			}
		}
		return implode('&', $out);
	}
}
}

if (!function_exists('sk_extract_params')) {
function sk_extract_params(string $request_uri, string $base, string $regex, array $map): array {
	$path = parse_url($request_uri, PHP_URL_PATH) ?? '';
	if ($base !== '' && str_starts_with($path, $base)) {
		$path = substr($path, strlen($base));
		if ($path === '') $path = '/';
	}
	if ($path !== '/' && str_ends_with($path, '/')) $path = rtrim($path, '/');
	if ($path === '') $path = '/';

	$m = [];
	if (!preg_match($regex, $path, $m)) return [];

	$params = [];
	foreach ($map as $idx => $name) {
		$i = (int)$idx;
		if (!isset($m[$i])) continue;
		if ($m[$i] === '') continue;
		$params[(string)$name] = rawurldecode($m[$i]);
	}
	return $params;
}
}

$__SK_RAW_BODY = null;
if (!function_exists('sk_request_body')) {
function sk_request_body(): string {
	global $__SK_RAW_BODY;
	if ($__SK_RAW_BODY === null) $__SK_RAW_BODY = file_get_contents('php://input') ?: '';
	return $__SK_RAW_BODY;
}
}

if (!function_exists('sk_json_body')) {
function sk_json_body() {
	$raw = sk_request_body();
	return json_decode($raw, true);
}
}

// Build param object similar to RequestEvent
if (!function_exists('sk_api_param')) {
function sk_api_param(): array {
	$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
	$headers = [];
	if (function_exists('getallheaders')) {
		$headers = getallheaders();
	} else {
		foreach ($_SERVER as $name => $value) {
			if (substr($name, 0, 5) == 'HTTP_') {
				$headers[str_replace(' ', '-', ucwords(strtolower(str_replace('_', ' ', substr($name, 5)))))] = $value;
			}
		}
	}

	$url = (object)[
		'searchParams' => new SK_URLSearchParams($_SERVER['QUERY_STRING'] ?? ''),
		'pathname' => parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH)
	];
	$locals = &sk_locals();

	return [
		'request' => (object)[
			'method' => $method,
			'headers' => $headers,
			'body' => sk_json_body(), // Default to parsed JSON for convenience
			'rawBody' => sk_request_body()
		],
		'url' => $url,
		'cookies' => new SK_Cookies($_COOKIE),
		'params' => sk_extract_params($_SERVER['REQUEST_URI'] ?? '', SK_BASE_PATH, SK_ROUTE_REGEX, SK_ROUTE_PARAM_MAP),
		'route' => (object)[
			'id' => '${prefix}'
		],
		'locals' => &$locals,
		'depends' => function(...$deps) {
			return null;
		},
		'fetch' => function($input, $init = []) {
			return sk_fetch($input, $init ?? []);
		}
	];
}
}

$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
$fn_name = '${prefix}_'.$method;

if (!function_exists($fn_name)) {
	// HEAD fallback to GET
	if ($method === 'HEAD' && function_exists('${prefix}_GET')) {
		$fn_name = '${prefix}_GET';
	} else {
		http_response_code(405);
		exit;
	}
}

$param = sk_api_param();

try {
	$res = $fn_name($param);
} catch (SK_Redirect $e) {
	header('Location: ' . $e->location, true, $e->status);
	exit;
} catch (SK_Error $e) {
	http_response_code($e->status);
	header('Content-Type: application/json; charset=utf-8');
	echo sk_json_encode(['type' => 'error', 'error' => $e->body, 'status' => $e->status]);
	exit;
} catch (Throwable $e) {
	http_response_code(500);
	error_log('[sveltekit-php] endpoint error: ' . $e->getMessage());
	header('Content-Type: text/plain; charset=utf-8');
	echo 'Internal Server Error';
	exit;
}

// Normalize response
$status = $res['status'] ?? 200;
$headers = $res['headers'] ?? [];
$body = $res['body'] ?? null;

// Apply headers
http_response_code((int)$status);
foreach($headers as $k => $v) {
	if (is_array($v)) {
		foreach($v as $val) {
			header("$k: $val", false);
		}
	} else {
		header("$k: $v");
	}
}

if ($body !== null) {
	$content = '';
	if (is_array($body) || is_object($body)) {
		if (!isset($headers['Content-Type']) && !isset($headers['content-type'])) {
			header('Content-Type: application/json');
		}
		$content = sk_json_encode($body);
	} else {
		$content = (string)$body;
	}

	if (!isset($headers['Content-Length']) && !isset($headers['content-length'])) {
		header('Content-Length: '.strlen($content));
	}

	if ($method !== 'HEAD') {
		echo $content;
	}
}
`;
}

export function getRouterPhp(base: string, mode: 'php-static' | 'js-ssr', fallback?: string | boolean) {
	let fallbackFile = 'index.php'; // default SPA fallback
	if (typeof fallback === 'string' && fallback) {
		fallbackFile = fallback;
	} else if (fallback === true) {
		fallbackFile = '200.html'; // Default Kit fallback
	}
	// If we converted .html to .php, we should look for .php version first or check both
	// In the template, we'll check for the file.

	const shared = getRouterSharedPhp(base);
	const routerBody =
		mode === 'php-static'
			? getRouterPhpStaticPhp(fallback, fallbackFile)
			: getRouterJsSsrPhp();
	return `${shared}${routerBody}
?>`;
}
