export function getDataPhp(
	includes: string[],
	base: string = '',
	compatRel: string = './_runtime/compat.php'
) {
	return `<?php
/**
 * Generated by @ryanspice/sveltekit-adapter-php
 * - Serves /__data.php requests (client navigation + invalidations)
 * - Provides sk_build_embed_data() for index.php hydration
 *
 * Template shape comes from prerendered __data.json (so it matches your Kit version).
 */

declare(strict_types=1);

require_once __DIR__ . '/${compatRel}';

// Allow env override for base path (e.g. for different dev/prod paths)
// Fallback to build-time base
define('SK_BASE_PATH', getenv('SK_BASE_PATH') ?: '${base}');
const SK_ROUTE_REGEX = 'PLACEHOLDER_ROUTE_REGEX';
const SK_ROUTE_PARAM_MAP = PLACEHOLDER_ROUTE_PARAM_MAP;

${includes.join('\n')}

function sk_json_encode($value): string {
	$json = json_encode(
		$value,
		JSON_UNESCAPED_SLASHES
			| JSON_UNESCAPED_UNICODE
			| JSON_HEX_TAG
			| JSON_HEX_AMP
			| JSON_HEX_APOS
			| JSON_HEX_QUOT
	);
	return $json === false ? 'null' : $json;
}

final class SK_URLSearchParams {
	private array $pairs = [];

	public function __construct(string $queryString) {
		$qs = ltrim($queryString, '?');
		if ($qs === '') return;
		foreach (explode('&', $qs) as $part) {
			if ($part === '') continue;
			$kv = explode('=', $part, 2);
			$key = urldecode($kv[0]);
			$val = urldecode($kv[1] ?? '');
			if (!array_key_exists($key, $this->pairs)) $this->pairs[$key] = [];
			$this->pairs[$key][] = $val;
		}
	}

	public function get(string $key): ?string {
		$vals = $this->pairs[$key] ?? null;
		if (!$vals) return null;
		return $vals[0] ?? null;
	}

	public function has(string $key): bool {
		return array_key_exists($key, $this->pairs);
	}

	public function __get(string $key): ?string {
		return $this->get($key);
	}

	public function __isset(string $key): bool {
		return $this->has($key);
	}

	public function all(string $key): array {
		return $this->pairs[$key] ?? [];
	}

	public function toString(): string {
		$out = [];
		foreach ($this->pairs as $k => $vals) {
			foreach ($vals as $v) {
				$out[] = rawurlencode($k) . '=' . rawurlencode($v);
			}
		}
		return implode('&', $out);
	}
}

final class __SK_Deferred {
	public $fn;
	public function __construct($fn) {
		$this->fn = $fn;
	}
}
final class __SK_Deferred_Placeholder {
	public int $id;
	public function __construct(int $id) {
		$this->id = $id;
	}
}

function sk_defer(callable $fn): __SK_Deferred { return new __SK_Deferred($fn); }

function sk_extract_params(string $request_uri, string $base, string $regex, array $map): array {
	$path = parse_url($request_uri, PHP_URL_PATH) ?? '';
	if ($base !== '' && str_starts_with($path, $base)) {
		$path = substr($path, strlen($base));
		if ($path === '') $path = '/';
	}

	if ($path !== '/' && str_ends_with($path, '/')) $path = rtrim($path, '/');
	if ($path === '') $path = '/';

	$m = [];
	if (!preg_match($regex, $path, $m)) return [];

	$params = [];
	foreach ($map as $idx => $name) {
		$i = (int)$idx;
		if (!isset($m[$i])) continue;
		if ($m[$i] === '') continue;
		$params[(string)$name] = rawurldecode($m[$i]);
	}

	return $params;
}

function sk_assert_jsonable($value, string $path = ''): void {
	if ($value instanceof __SK_Deferred || $value instanceof __SK_Deferred_Placeholder) return;
	if (is_null($value) || is_bool($value) || is_int($value) || is_string($value)) return;
	if (is_float($value)) {
		if (is_nan($value) || is_infinite($value)) {
			throw new RuntimeException("Non-JSON float at $path");
		}
		return;
	}
	if (is_array($value)) {
		foreach ($value as $k => $v) {
			$next = $path === '' ? (string)$k : ($path . '.' . (string)$k);
			sk_assert_jsonable($v, $next);
		}
		return;
	}
	if (is_object($value)) {
		if ($value instanceof JsonSerializable) {
			sk_assert_jsonable($value->jsonSerialize(), $path);
			return;
		}
		throw new RuntimeException("Non-JSON object at $path");
	}
	if (is_resource($value)) throw new RuntimeException("Non-JSON resource at $path");
	throw new RuntimeException("Non-JSON value at $path");
}

function sk_recursive_resolve($data, ?array &$deferreds = null) {
	if ($data instanceof __SK_Deferred) {
		if ($deferreds !== null) {
			$id = count($deferreds);
			$deferreds[] = $data;
			return new __SK_Deferred_Placeholder($id);
		}
		$fn = $data->fn;
		return sk_recursive_resolve($fn(), $deferreds);
	}
	if (is_array($data)) {
		foreach ($data as $k => $v) {
			$data[$k] = sk_recursive_resolve($v, $deferreds);
		}
	}
	return $data;
}

/**
 * Locates the "nodes" array within the template payload.
 * Supports:
 *   A) { "type":"data", "nodes":[ ... ] }
 *   B) devalue-like: [ { "type":1, "nodes":2 }, ..., <nodes at index 2>, ... ]
 */
function sk_get_nodes_ref(array &$payload): array {
	// A) associative with nodes
	if (array_key_exists('nodes', $payload) && is_array($payload['nodes'])) {
		return ['kind' => 'assoc', 'key' => 'nodes'];
	}

	// B) packed array with header object at 0
	if (isset($payload[0]) && is_array($payload[0]) && array_key_exists('nodes', $payload[0]) && is_int($payload[0]['nodes'])) {
		$idx = $payload[0]['nodes'];
		if (isset($payload[$idx]) && is_array($payload[$idx])) {
			return ['kind' => 'index', 'idx' => $idx];
		}
	}

	// fallback: treat as already nodes
	return ['kind' => 'self'];
}

function sk_serialize($value): array {
	$flattened = [];
	$map = [];

	// Recursive closure to flatten the structure
	// We use a reference for $flattened to append values
	$fn = function($val) use (&$flattened, &$map, &$fn) {
		// Primitives
		if (is_string($val) || is_int($val) || is_float($val) || is_bool($val) || is_null($val)) {
			$key = is_string($val) ? 's_'.$val : (is_int($val) ? 'i_'.$val : (is_float($val) ? 'f_'.$val : json_encode($val)));
			if (array_key_exists($key, $map)) {
				return $map[$key];
			}

			$flattened[] = $val;
			$idx = count($flattened) - 1;
			$map[$key] = $idx;
			return $idx;
		}

		if ($val instanceof __SK_Deferred_Placeholder) {
			// Placeholder for deferred promise
			// We return a unique string that we can replace later
			$placeholder = "%%%SK_DEFER_" . $val->id . "%%%";
			$flattened[] = $placeholder;
			return count($flattened) - 1;
		}

		// Arrays / Objects
		// Detect if it's a list (array) or object (associative)
		$is_list = is_array($val) && array_is_list($val);
		$flattened[] = $is_list ? [] : (object)[];
		$idx = count($flattened) - 1;
		$map['o_'.$idx] = $idx; // Object identity is hard to dedupe perfectly, simplified

		foreach ($val as $k => $v) {
			$vIdx = $fn($v);
			if (is_array($flattened[$idx])) {
				$flattened[$idx][] = $vIdx;
			} else {
				$flattened[$idx]->{$k} = $vIdx;
			}
		}
		return $idx;
	};

	$fn($value);
	return $flattened;
}

/**
 * Unflattens a Devalue-serialized array back into a PHP structure (array/object).
 * This is used to provide hydrated data to the client in a format SvelteKit's start() accepts (objects).
 */
function sk_unflatten(array $data) {
	if (empty($data)) return null;

	$resolve = function($idx) use ($data, &$resolve) {
		$val = $data[$idx] ?? null;

		// Primitives are returned as-is
		if (!is_array($val) && !is_object($val)) {
			return $val;
		}

		// Handle stdClass (from sk_serialize)
		if (is_object($val)) {
			$val = (array)$val;
			$res = (object)[];
			foreach ($val as $k => $i) {
				$res->{$k} = $resolve($i);
			}
			return $res;
		}

		// Handle arrays (from json_decode or sk_serialize)
		// Check for array vs object (associative)
		// Polyfill for array_is_list: keys are 0..count-1
		$is_list = $val === [] || (array_keys($val) === range(0, count($val) - 1));

		if ($is_list) {
			$res = [];
			foreach ($val as $i) {
				$res[] = $resolve($i);
			}
			return $res;
		} else {
			$res = (object)[];
			foreach ($val as $k => $i) {
				$res->{$k} = $resolve($i);
			}
			return $res;
		}
	};

	// Devalue root is always at index 0
	return $resolve(0);
}

function sk_set_node_data(&$node, $server_data): void {
	if (!is_array($node)) {
		$node = [];
	}

	sk_assert_jsonable($server_data);

	// SvelteKit expects data to be the serialized array (devalue format).
	// We use sk_serialize to produce a devalue-compatible flattened array.
	// We force array_values to ensure it's encoded as a JSON list, not an object.
	$encoded = sk_serialize($server_data);
	$node['data'] = array_values($encoded);

	$node['uses'] = $node['uses'] ?? (object)[];
	// Force uses to be an object if it's an empty array
	if (is_array($node['uses']) && count($node['uses']) === 0) {
		$node['uses'] = (object)[];
	}
}

function sk_set_payload_form(&$payload, $form): void {
	if (is_array($payload) && isset($payload[0]) && is_array($payload[0])) {
		$payload[0]['form'] = $form;
		return;
	}

	if (is_array($payload)) {
		$payload['form'] = $form;
	}
}

function sk_apply_loads(string $routeid, array $loadFns, array &$payload, string $inline_mode, ?array &$deferreds = null): array {
	$base = [];
	$server_results = [];
	$next_chunk_id = 1;
	$params = sk_extract_params($_SERVER['REQUEST_URI'] ?? '', SK_BASE_PATH, SK_ROUTE_REGEX, SK_ROUTE_PARAM_MAP);

	// Loop through load functions (from root layout to leaf page)
	foreach ($loadFns as $i => $fn) {
		if (!function_exists($fn)) {
			continue;
		}

		// Prepare URL object to match dev environment
		$searchParams = new SK_URLSearchParams($_SERVER['QUERY_STRING'] ?? '');

		// Execute the load function
		// Pass $base (merged parent data) as 'parentdata' if needed, though SvelteKit usually
		// passes a parent() function. For this simple adapter, we simulate parent merging
		// by accumulating data in $base.
		$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
		$locals = &sk_locals();

		try {
			$res = $fn([
				'params' => $params,
				'url' => (object)[
					'searchParams' => $searchParams,
					'pathname' => $_SERVER['REQUEST_URI'] ?? ''
				],
				'request' => (object)[
					'method' => $method,
					'headers' => (object)[
						'cookie' => $_SERVER['HTTP_COOKIE'] ?? ''
					]
				],
				'cookies' => new SK_Cookies($_COOKIE),
				'route' => (object)[
					'id' => $routeid
				],
				'parent' => function() use (&$base) {
					return $base;
				},
				'locals' => &$locals,
				'depends' => function(...$deps) {
					return null;
				},
				'fetch' => function($input, $init = []) {
					return sk_fetch($input, $init ?? []);
				},
				'routeid' => $routeid,
				'parentdata' => $base,
				'method' => $method,
				'query' => $_GET,
				'server' => $_SERVER
			]);
		} catch (SK_Redirect $e) {
			header('Location: ' . $e->location, true, $e->status);
			exit;
		} catch (SK_Error $e) {
			http_response_code($e->status);
			echo sk_json_encode(['error' => $e->body]);
			exit;
		}

		// Merge result into base for next level
		if (is_array($res)) {
			$res = sk_recursive_resolve($res, $deferreds);
			$base = array_merge($base, $res);
			$server_results[$i] = $res;
		} else {
			// Handle non-array results? (e.g. redirect/error usually throw)
			$res = sk_recursive_resolve($res, $deferreds);
			$server_results[$i] = $res;
		}
	}

	// Update the payload with server results
	$ref = sk_get_nodes_ref($payload);

	// Helper to access nodes array by reference
	$nodes = [];
	if ($ref['kind'] === 'assoc') {
		$nodes = &$payload[$ref['key']];
	} elseif ($ref['kind'] === 'index') {
		$nodes = &$payload[$ref['idx']];
	} else {
		$nodes = &$payload;
	}

	foreach ($server_results as $i => $data) {
		// Map load index to node index
		// $i is string (key from loadFns)
		$nodeIdx = $i;

		if (array_key_exists($nodeIdx, $nodes)) {
			sk_set_node_data($nodes[$nodeIdx], $data);
		}
	}

	// Inline Mode: return full payload (no streaming needed for now)
	return $payload;
}

function sk_build_embed_data(string $routeid, array $loadFns, string $templateJson, string $inline_mode, bool $streaming = false): array {
	$payload = json_decode($templateJson, true);
	if (!$payload) return ['[]', []];

	$deferreds = $streaming ? [] : null;
	$finalPayload = sk_apply_loads($routeid, $loadFns, $payload, $inline_mode, $deferreds);
	if (array_key_exists('__SK_ACTION_RESULT', $GLOBALS)) {
		sk_set_payload_form($finalPayload, $GLOBALS['__SK_ACTION_RESULT']);
	}

	// Extract nodes to generate the hydration array
	$ref = sk_get_nodes_ref($finalPayload);
	$nodes = [];
	if ($ref['kind'] === 'assoc') {
		$nodes = $finalPayload[$ref['key']];
	} elseif ($ref['kind'] === 'index') {
		$nodes = $finalPayload[$ref['idx']];
	} else {
		$nodes = $finalPayload;
	}

	$outputPayload = $finalPayload;

	// If inline_mode is 'nodes', we want the parallel array of data objects
	// SvelteKit hydration expects [ data_0, data_1, ... ] matching node_ids
	// We must unflatten the Devalue structure to provide plain objects to SvelteKit's start()
	if ($inline_mode === 'nodes' || $inline_mode === 'unknown') {
		$hydrationData = [];
		if (is_array($nodes)) {
			foreach ($nodes as $node) {
				$data = $node['data'] ?? null;
				$newNode = $node;
				if (is_array($data)) {
					$newNode['data'] = sk_unflatten($data);
				}
				$hydrationData[] = $newNode;
			}
		}
		$outputPayload = $hydrationData;
	}

	$json = sk_json_encode($outputPayload);

	// Replace deferred placeholders with JS calls
	if ($streaming && $deferreds) {
		// We need to be careful not to replace things inside strings that look like our marker,
		// but our marker is very specific.
		// The marker is "%%%SK_DEFER_ID%%%" (quoted in JSON).
		// We want to replace "%%%SK_DEFER_ID%%%" with PLACEHOLDER_APP_ID.defer(ID).
		// Note the lack of quotes in the replacement.

		$json = preg_replace_callback('/"%%%SK_DEFER_(\\d+)%%%"/', function($matches) {
			$id = (int)$matches[1];
			// SvelteKit uses 1-based IDs usually? We used 0-based index in array, so +1?
			// sk_recursive_resolve used count($deferreds) BEFORE push. So 0-based.
			// Let's use the ID as is.
			return "PLACEHOLDER_APP_ID.defer($id)";
		}, $json);
	}

	return [$json, $deferreds];
}

// Main execution if called directly (client navigation)
if (basename($_SERVER['SCRIPT_FILENAME']) === '__data.php') {
	header('Content-Type: application/json; charset=utf-8');

    // Intercept redirects to ensure they point to __data.json
    // This fixes the issue where SvelteKit client navigation receives HTML instead of JSON
    // when a load function redirects to a page URL.
    register_shutdown_function(function() {
        if (headers_sent()) return;

        $headers = headers_list();
        foreach ($headers as $h) {
            // Case-insensitive check for Location header
            if (stripos($h, 'Location:') === 0) {
                $location = trim(substr($h, 9));

                // If redirecting to a page (not already __data.json)
                if (strpos($location, '__data.json') === false) {
                    // Only rewrite local paths (starting with /)
                    // This covers most SvelteKit redirects.
                    if (strpos($location, '/') === 0) {
                         $parts = parse_url($location);
                         $path = $parts['path'] ?? '';

                         // Append /__data.json
                         // SvelteKit normalization usually strips trailing slash, but we are appending a file.
                         // /foo -> /foo/__data.json
                         // /foo/ -> /foo/__data.json
                         $newPath = rtrim($path, '/') . '/__data.json';
						 if (SK_BASE_PATH !== '' && strpos($newPath, SK_BASE_PATH . '/') !== 0 && $newPath !== SK_BASE_PATH) {
							 $newPath = SK_BASE_PATH . $newPath;
						 }

                         $newLocation = $newPath;
                         if (isset($parts['query'])) $newLocation .= '?' . $parts['query'];
                         if (isset($parts['fragment'])) $newLocation .= '#' . $parts['fragment'];

                         // Replace the Location header
                         header("Location: $newLocation", true);
                    }
                }
            }
        }
	});

	// Execute loads
	$templateJson = base64_decode('PLACEHOLDER_TEMPLATE_B64');
	$payload = json_decode(is_string($templateJson) ? $templateJson : '', true);
	$loadFns = PLACEHOLDER_LOAD_FNS;
	$routeId = PLACEHOLDER_ROUTE_ID;
	$inlineMode = PLACEHOLDER_INLINE_MODE;

	// Blocking mode for client navigation
	$finalPayload = sk_apply_loads($routeId, $loadFns, $payload, $inlineMode);
	$json = sk_json_encode($finalPayload);

    header('Content-Length: ' . strlen($json));

    if ($_SERVER['REQUEST_METHOD'] !== 'HEAD') {
        echo $json;
    }
}
`;
}

export function getActionPhp(
	includes: string[],
	routeId: string,
	pagePrefix: string | null,
	compatRel: string = './_runtime/compat.php'
) {
	return `<?php
/**
 * Generated by @ryanspice/sveltekit-adapter-php
 * - Handles form actions (POST)
 */

declare(strict_types = 1);

require_once __DIR__ . '/${compatRel}';

${includes.join('\n')}

require_once __DIR__ . '/__data.php';

// Helper for SvelteKit fail()
function sk_fail(int $status, $data): array {
	return ['type' => 'failure', 'status' => $status, 'data' => $data];
}

function sk_action_serialize($value): string {
	return sk_json_encode(array_values(sk_serialize($value)));
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
	http_response_code(405);
	exit('Method Not Allowed');
}

// 1. Determine Action Name
// SvelteKit passes action name in query string usually ?/actionName
// Or default action if ?/
$actionName = 'default';
foreach($_GET as $key => $val) {
	if (str_starts_with($key, '/')) {
		$name = substr($key, 1);
		$actionName = $name === '' ? 'default' : $name;
		break;
	}
}

// 2. Call the action
$isEnhanced = (($_SERVER['HTTP_X_SVELTEKIT_ACTION'] ?? '') === 'true');
$pagePrefix = ${pagePrefix ? `'${pagePrefix}'` : "''"};
$fnName = $pagePrefix . '_action_' . $actionName;

if (!function_exists($fnName)) {
	http_response_code(404);
	header('Content-Type: application/json; charset=utf-8');
	echo sk_json_encode(['type' => 'error', 'error' => ['message' => 'Action not found']]);
	exit;
}

// 3. Execute
// We need to parse body (multipart or urlencoded)
// PHP does this automatically into $_POST and $_FILES

try {
	$params = sk_extract_params($_SERVER['REQUEST_URI'] ?? '', SK_BASE_PATH, SK_ROUTE_REGEX, SK_ROUTE_PARAM_MAP);
	$method = $_SERVER['REQUEST_METHOD'] ?? 'POST';
	$locals = &sk_locals();

	$result = $fnName([
		'request' => (object)[
			'method' => $method,
			'formData' => function () {
				return array_merge($_POST, $_FILES);
			}
		],
		'url' => (object)[
			'searchParams' => new SK_URLSearchParams($_SERVER['QUERY_STRING'] ?? ''),
			'pathname' => parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH)
		],
		'params' => $params,
		'route' => (object)[
			'id' => ${JSON.stringify(routeId)}
		],
		'locals' => &$locals,
		'depends' => function(...$deps) {
			return null;
		},
		'fetch' => function($input, $init = []) {
			return sk_fetch($input, $init ?? []);
		},
		'cookies' => new SK_Cookies($_COOKIE),
		'post' => $_POST,
		'files' => $_FILES
    ]);

	// 4. Return result
	// SvelteKit actions return { type: 'success'|'failure'|'redirect'|'error', data: ... }
	// We assume the PHP code returns an array/object matching this.

	if ($isEnhanced) {
		header('Content-Type: application/json; charset=utf-8');
		echo sk_action_serialize($result);
		exit;
	}

	$accept = $_SERVER['HTTP_ACCEPT'] ?? '';
	$expectsJson = strpos($accept, 'application/json') !== false;

	if (isset($result['type']) && $result['type'] === 'redirect') {
		if ($expectsJson) {
			header('Content-Type: application/json; charset=utf-8');
			echo sk_json_encode($result);
			exit;
		}

		header('Location: '.$result['location']);
		http_response_code($result['status'] ?? 303);
		exit;
	}

	if ($expectsJson) {
		header('Content-Type: application/json; charset=utf-8');
		echo sk_json_encode($result);
		exit;
	}

	if (isset($result['type']) && $result['type'] === 'failure') {
		http_response_code($result['status'] ?? 400);
		$GLOBALS['__SK_ACTION_RESULT'] = $result['data'] ?? null;
		return;
	}

	if (isset($result['type']) && $result['type'] === 'error') {
		http_response_code($result['status'] ?? 500);
		$GLOBALS['__SK_ACTION_RESULT'] = $result['error'] ?? null;
		return;
	}

	if (isset($result['type']) && $result['type'] === 'success') {
		$GLOBALS['__SK_ACTION_RESULT'] = $result['data'] ?? null;
		return;
	}

	if (is_array($result)) {
		$GLOBALS['__SK_ACTION_RESULT'] = $result;
		return;
	}

	http_response_code(500);

} catch (SK_Redirect $e) {
	if (!$isEnhanced) {
		header('Location: ' . $e->location, true, $e->status);
		exit;
	}
	header('Content-Type: application/json; charset=utf-8');
	echo sk_json_encode(['type' => 'redirect', 'location' => $e->location, 'status' => $e->status]);
	exit;
} catch (SK_Error $e) {
	http_response_code($e->status);
	if ($isEnhanced) {
		header('Content-Type: application/json; charset=utf-8');
		echo sk_json_encode(['type' => 'error', 'error' => $e->body, 'status' => $e->status]);
		exit;
	}
	$GLOBALS['__SK_ACTION_RESULT'] = $e->body;
	return;
} catch (Throwable $e) {
	http_response_code(500);
	header('Content-Type: application/json; charset=utf-8');
    echo sk_json_encode(['type' => 'error', 'error' => ['message' => $e -> getMessage()]]);
}
`;
}

export function getBootstrapPhp(
	routeId: string,
	loadFns: string,
	templateJson: string,
	inlineMode: string,
	requirePrefix: string = ''
) {
	const templateB64 = Buffer.from(templateJson, 'utf8').toString('base64');
	return `<?php
require_once __DIR__ . '${requirePrefix}/__data.php';

ini_set('output_buffering', '0');
ini_set('zlib.output_compression', '0');
ini_set('implicit_flush', '1');
while (ob_get_level()) ob_end_flush();

// Handle Actions (POST)
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (file_exists(__DIR__ . '${requirePrefix}/__action.php')) {
        require __DIR__ . '${requirePrefix}/__action.php';
    }
}

$routeId = ${JSON.stringify(routeId)};
$loadFns = ${loadFns};
$templateJson = base64_decode('${templateB64}');
$inlineMode = ${JSON.stringify(inlineMode)};

// Build data with streaming support
list($dataPayload, $sk_deferreds) = sk_build_embed_data($routeId, $loadFns, $templateJson, $inlineMode, true);

// Fix PLACEHOLDER_APP_ID in streaming promises
// We can't do this in sk_build_embed_data because we don't know the appId yet
// But wait, sk_build_embed_data returns JSON string with placeholders if we used PLACEHOLDER_APP_ID.
// The regex in sk_build_embed_data replaced the deferred marker with a JS call.
// We need to replace PLACEHOLDER_APP_ID with the actual appId found in HTML.
// But we find appId AFTER generating this PHP block.
// Solution: We inject a PHP variable for appId, or we rely on the client-side variable being available.
// SvelteKit usually assigns the app to a variable like '__sveltekit_xyz'.
// We need to ensure our injected script uses the CORRECT variable.
// But we are prepending PHP.
// We can use a JS variable that we define? No, SvelteKit defines it.

// Let's assume we can replace it in the output HTML buffer or we inject a script that defines a bridge.
// OR we just use 'document.currentScript.parentElement' context? No, defer calls are global.

// Revert to using a known variable if possible, or parsing it.
// The adapter index.ts finds the appHash and passes it to getFooterPhp.
// Can we pass it to getBootstrapPhp?
// Yes, we call getBootstrapPhp in index.ts. We should pass appHash there.
?>`;
}

export function getFooterPhp(appId: string) {
	return `<?php
// Footer to handle streaming
// Flush HTML
while (ob_get_level()) ob_end_flush();
flush();

if (!empty($sk_deferreds)) {
	foreach($sk_deferreds as $id => $deferred) {
		$fn = $deferred -> fn;
		// Resolve
		// We use sk_recursive_resolve to resolve the deferred value (blocking for this chunk)
		$data = sk_recursive_resolve($fn());

		// Serialize
		$serialized = sk_json_encode(array_values(sk_serialize($data)));

		// Output script to resolve the promise on the client
		// We use the global variable '${appId}' detected during build.
		echo '<script>if(typeof ${appId} !== "undefined") ${appId}.resolve('.$id. ', () => '.$serialized. ');</script>';
		flush();
	}
}
?>`;
}

export function getMinimalBootstrapPhp(requirePrefix: string = '') {
	return `<?php
// Minimal bootstrap for actions only (SSR=false or no data)
// We still might need __action.php included if we want to support actions on this page
// (even if data loading is client-side).
if (file_exists(__DIR__. '${requirePrefix}/__action.php')) {
	// require_once __DIR__ . '${requirePrefix}/__action.php';
	// Actually, actions are POST requests to ?/action, handled by __action.php directly?
	// Or does the page need to know about them?
	// Usually no.
}
`;
}

export function getApiPhp(
	includes: string[],
	prefix: string,
	base: string,
	routeRegex: string,
	routeParamMapPhp: string,
	compatRel: string = './_runtime/compat.php'
) {
	return `<?php
/**
 * Generated by @ryanspice/sveltekit-adapter-php
 * - Handles API endpoints (+server.php)
 */
declare(strict_types=1);

require_once __DIR__ . '/${compatRel}';

// Allow env override for base path
define('SK_BASE_PATH', getenv('SK_BASE_PATH') ?: '${base}');
const SK_ROUTE_REGEX = '${routeRegex}';
const SK_ROUTE_PARAM_MAP = ${routeParamMapPhp};

${includes.join('\n')}

function sk_json_encode($value): string {
	$json = json_encode(
		$value,
		JSON_UNESCAPED_SLASHES
			| JSON_UNESCAPED_UNICODE
			| JSON_HEX_TAG
			| JSON_HEX_AMP
			| JSON_HEX_APOS
			| JSON_HEX_QUOT
	);
	return $json === false ? 'null' : $json;
}

final class SK_URLSearchParams {
	private array $pairs = [];

	public function __construct(string $queryString) {
		$qs = ltrim($queryString, '?');
		if ($qs === '') return;
		foreach (explode('&', $qs) as $part) {
			if ($part === '') continue;
			$kv = explode('=', $part, 2);
			$key = urldecode($kv[0]);
			$val = urldecode($kv[1] ?? '');
			if (!array_key_exists($key, $this->pairs)) $this->pairs[$key] = [];
			$this->pairs[$key][] = $val;
		}
	}

	public function get(string $key): ?string {
		$vals = $this->pairs[$key] ?? null;
		if (!$vals) return null;
		return $vals[0] ?? null;
	}

	public function has(string $key): bool {
		return array_key_exists($key, $this->pairs);
	}

	public function all(string $key): array {
		return $this->pairs[$key] ?? [];
	}

	public function toString(): string {
		$out = [];
		foreach ($this->pairs as $k => $vals) {
			foreach ($vals as $v) {
				$out[] = rawurlencode($k) . '=' . rawurlencode($v);
			}
		}
		return implode('&', $out);
	}
}

function sk_extract_params(string $request_uri, string $base, string $regex, array $map): array {
	$path = parse_url($request_uri, PHP_URL_PATH) ?? '';
	if ($base !== '' && str_starts_with($path, $base)) {
		$path = substr($path, strlen($base));
		if ($path === '') $path = '/';
	}
	if ($path !== '/' && str_ends_with($path, '/')) $path = rtrim($path, '/');
	if ($path === '') $path = '/';

	$m = [];
	if (!preg_match($regex, $path, $m)) return [];

	$params = [];
	foreach ($map as $idx => $name) {
		$i = (int)$idx;
		if (!isset($m[$i])) continue;
		if ($m[$i] === '') continue;
		$params[(string)$name] = rawurldecode($m[$i]);
	}
	return $params;
}

$__SK_RAW_BODY = null;
function sk_request_body(): string {
	global $__SK_RAW_BODY;
	if ($__SK_RAW_BODY === null) $__SK_RAW_BODY = file_get_contents('php://input') ?: '';
	return $__SK_RAW_BODY;
}

function sk_json_body() {
	$raw = sk_request_body();
	return json_decode($raw, true);
}

// Build param object similar to RequestEvent
function sk_api_param(): array {
	$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
	$headers = [];
	if (function_exists('getallheaders')) {
		$headers = getallheaders();
	} else {
		foreach ($_SERVER as $name => $value) {
			if (substr($name, 0, 5) == 'HTTP_') {
				$headers[str_replace(' ', '-', ucwords(strtolower(str_replace('_', ' ', substr($name, 5)))))] = $value;
			}
		}
	}

	$url = (object)[
		'searchParams' => new SK_URLSearchParams($_SERVER['QUERY_STRING'] ?? ''),
		'pathname' => parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH)
	];
	$locals = &sk_locals();

	return [
		'request' => (object)[
			'method' => $method,
			'headers' => $headers,
			'body' => sk_json_body(), // Default to parsed JSON for convenience
			'rawBody' => sk_request_body()
		],
		'url' => $url,
		'cookies' => new SK_Cookies($_COOKIE),
		'params' => sk_extract_params($_SERVER['REQUEST_URI'] ?? '', SK_BASE_PATH, SK_ROUTE_REGEX, SK_ROUTE_PARAM_MAP),
		'route' => (object)[
			'id' => '${prefix}'
		],
		'locals' => &$locals,
		'depends' => function(...$deps) {
			return null;
		},
		'fetch' => function($input, $init = []) {
			return sk_fetch($input, $init ?? []);
		}
	];
}

$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
$fn_name = '${prefix}_'.$method;

if (!function_exists($fn_name)) {
	// HEAD fallback to GET
	if ($method === 'HEAD' && function_exists('${prefix}_GET')) {
		$fn_name = '${prefix}_GET';
	} else {
		http_response_code(405);
		exit;
	}
}

$param = sk_api_param();

try {
	$res = $fn_name($param);
} catch (SK_Redirect $e) {
	header('Location: ' . $e->location, true, $e->status);
	exit;
} catch (SK_Error $e) {
	http_response_code($e->status);
	header('Content-Type: application/json; charset=utf-8');
	echo sk_json_encode(['type' => 'error', 'error' => $e->body, 'status' => $e->status]);
	exit;
} catch (Throwable $e) {
	http_response_code(500);
	// In dev, show error. In prod, maybe generic?
	// For now, simple text output
	echo "Internal Server Error: ".$e -> getMessage();
	exit;
}

// Normalize response
$status = $res['status'] ?? 200;
$headers = $res['headers'] ?? [];
$body = $res['body'] ?? null;

// Apply headers
http_response_code((int)$status);
foreach($headers as $k => $v) {
	if (is_array($v)) {
		foreach($v as $val) {
			header("$k: $val", false);
		}
	} else {
		header("$k: $v");
	}
}

if ($body !== null) {
	$content = '';
	if (is_array($body) || is_object($body)) {
		if (!isset($headers['Content-Type']) && !isset($headers['content-type'])) {
			header('Content-Type: application/json');
		}
		$content = sk_json_encode($body);
	} else {
		$content = (string)$body;
	}

	if (!isset($headers['Content-Length']) && !isset($headers['content-length'])) {
		header('Content-Length: '.strlen($content));
	}

	if ($method !== 'HEAD') {
		echo $content;
	}
}
`;
}

export function getRouterPhp(base: string, mode: 'php-static' | 'node-ssr') {
	return `<?php
// Simple router to emulate Apache .htaccess mod_rewrite
// for the PHP built-in server.
// Generated by @ryanspice/sveltekit-adapter-php

require_once __DIR__ . '/_runtime/compat.php';

// Helper for logging
function router_log($msg) {
	file_put_contents('php://stderr', "[Router] ".$msg. "\\n", FILE_APPEND);
}

$uri = urldecode(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH));
$base = getenv('SK_BASE_PATH') ?: '${base}';

router_log("Request: $uri");

// Strip base path
if ($base !== '' && strpos($uri, $base) === 0) {
	$uri = substr($uri, strlen($base));
	if ($uri === '' || $uri === false) $uri = '/';
	router_log("Stripped URI: $uri");
}

// Security: Block _protected directory
if (strpos($uri, '/_protected/') === 0) {
	http_response_code(403);
    echo "Access Denied";
	return;
}

${mode === 'php-static'
			? `
// Canonicalize /foo/ -> /foo (prevents relative asset paths breaking hydration)
if ($uri !== '/' && str_ends_with($uri, '/')) {
    $qs = $_SERVER['QUERY_STRING'] ?? '';
    $location = $base . rtrim($uri, '/');
    if ($location === '') $location = $base ?: '/';
    if ($qs !== '') $location .= '?' . $qs;
    header('Location: ' . $location, true, 308);
    return;
}

// Normalize: treat /foo and /foo/ identically
$uri = rtrim($uri, '/');
if ($uri === '') $uri = '/';

// Special handling for SvelteKit __data.json requests
// Map /path/__data.json to /path/__data.php
$suffix = '/__data.json';
if (substr($uri, -strlen($suffix)) === $suffix) {
    $php_file_rel = str_replace($suffix, '/__data.php', $uri);
    $php_file = __DIR__ . $php_file_rel; // Flat build structure

    if (file_exists($php_file)) {
        router_log("Mapping JSON to PHP: $uri -> $php_file");
        header('Content-Type: application/json');
        header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
        $_SERVER['SCRIPT_FILENAME'] = realpath($php_file);
        require $php_file;
        return;
    } else {
        // Do not fallback to index.php for __data.json
        http_response_code(404);
        echo json_encode(["error" => "Data not found", "path" => $uri]);
        return;
    }
}
`
			: `
// node-ssr mode: Do NOT rewrite __data.json to __data.php
// Instead, let it fall through to the Proxy (index.php) which forwards to sidecar.
`
		}

// 1. Serve static files if they exist
$path = __DIR__.$uri;
if ($uri !== '/' && file_exists($path) && is_file($path)) {
	// HEAD Support for static files
	if ($_SERVER['REQUEST_METHOD'] === 'HEAD') {
		$ext = pathinfo($path, PATHINFO_EXTENSION);
		$mimes = [
			'js' => 'application/javascript',
			'mjs' => 'application/javascript',
			'cjs' => 'application/javascript',
			'css' => 'text/css',
			'json' => 'application/json',
			'html' => 'text/html',
			'htm' => 'text/html',
			'xml' => 'text/xml',
			'txt' => 'text/plain',
			'svg' => 'image/svg+xml',
			'png' => 'image/png',
			'jpg' => 'image/jpeg',
			'jpeg' => 'image/jpeg',
			'gif' => 'image/gif',
			'webp' => 'image/webp',
			'ico' => 'image/x-icon'
		];
		$mime = $mimes[$ext] ?? (mime_content_type($path) ?: 'application/octet-stream');
		header('Content-Type: '.$mime);
		header('Content-Length: '.filesize($path));
		return;
	}
	return false; // serve as-is
}

${mode === 'php-static'
			? `
// 2. If it's a directory, manually serve index.php or index.html
if ($uri !== '/' && is_dir($path)) {
    foreach (['/index.php', '/index.html'] as $idx) {
        $candidate = $path . $idx;
        if (is_file($candidate)) {
            if (str_ends_with($candidate, '.php')) {
                $requested_file = realpath($candidate);
                if ($requested_file) {
                    router_log("Serving Directory Index PHP: $requested_file");
                    $_SERVER['SCRIPT_FILENAME'] = $requested_file;
                    require $requested_file;
                    return;
                }
            }

            router_log("Serving Directory Index HTML: $candidate");
            header('content-type: text/html; charset=utf-8');
            readfile($candidate);
            return;
        }
    }
}

// 3. Extensionless matching: /foo -> /foo.php or /foo.html
if ($uri !== '/') {
    foreach (['.php', '.html'] as $ext) {
        $candidate = $path . $ext;
        if (is_file($candidate)) {
            if ($ext === '.php') {
                $requested_file = realpath($candidate);
                if ($requested_file) {
                    router_log("Serving PHP file: $requested_file");
                    $_SERVER['SCRIPT_FILENAME'] = $requested_file;
                    require $requested_file;
                    return;
                }
            }

            router_log("Serving HTML file: $candidate");
            header('content-type: text/html; charset=utf-8');
            readfile($candidate);
            return;
        }
    }
}

// 4. Do not fallback API 404s to HTML
if ($uri === '/api' || str_starts_with($uri, '/api/')) {
    http_response_code(404);
    echo "404 Not Found (PHP Router)";
    return;
}

// 5. SPA/dynamic fallback for non-prerendered routes:
// prefer index.php if present, otherwise index.html
$fallback_php = __DIR__ . '/index.php';
$fallback_html = __DIR__ . '/index.html';

if (is_file($fallback_php)) {
    router_log("Serving Root Index PHP (Fallback): $fallback_php");
    $_SERVER['SCRIPT_FILENAME'] = realpath($fallback_php);
    require $fallback_php;
    return;
}

if (is_file($fallback_html)) {
    router_log("Serving Root Index HTML (Fallback): $fallback_html");
    header('content-type: text/html; charset=utf-8');
    readfile($fallback_html);
    return;
}

http_response_code(404);
echo "404 Not Found (PHP Router)";
return;
`
			: `
// 2. Serve PHP endpoints (directories with index.php)
// This handles +server.php which are copied to out/path/index.php
if (file_exists($path) && is_dir($path) && file_exists($path . '/index.php')) {
    // Check if it's a wrapper (has _server.php)
    if (file_exists($path . '/_server.php')) {
        $file = realpath($path . '/index.php');
        $_SERVER['SCRIPT_FILENAME'] = $file;
        require $file;
        return;
    }

    // If not a wrapper, it might be the Proxy (at root).
    // If index.html exists, serve it (Prerendered Page takes precedence over Proxy for HTML)
    if (file_exists($path . '/index.html')) {
        header('Content-Type: text/html');
        readfile($path . '/index.html');
        return;
    }

    $file = realpath($path . '/index.php');
    $_SERVER['SCRIPT_FILENAME'] = $file;
    require $file;
    return;
}

// Mode B: Fallback to Proxy (index.php)

// Check for index.html in the requested directory (Prerendered)
router_log("Checking index.html in path: $path");
if (is_dir($path)) {
    $index = rtrim($path, '/') . '/index.html';
    if (file_exists($index)) {
        router_log("Serving Prerendered Index: $index");
        header('Content-Type: text/html');
        readfile($index);
        return;
    } else {
        router_log("Prerendered Index not found: $index");
    }
} else {
    router_log("Not a directory: $path");
}

if (file_exists(__DIR__ . '/index.php')) {
    $file = realpath(__DIR__ . '/index.php');
    $_SERVER['SCRIPT_FILENAME'] = $file;
    // We must pass the original URI to the proxy (or stripped? Proxy expects stripped if base is set)
    // Actually, if we require index.php, it will read $_SERVER['REQUEST_URI'].
    // If router.php strips it, it only affects local $uri variable.
    // We should probably rely on index.php to handle the URI.
    require $file;
    return;
}
`
		}
`;
}
